import * as React from "react";
import Box from "@mui/joy/Box";
import LinearProgress from "@mui/joy/LinearProgress";
import Sheet from "@mui/joy/Sheet";
import Stack from "@mui/joy/Stack";
import Typography from "@mui/joy/Typography";
import { Check, Database, FileSpreadsheet, PlugZap, Sparkles, UploadCloud } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { JoyButton } from "@/components/joy/JoyButton";
import { JoyCard, JoyCardContent, JoyCardHeader } from "@/components/joy/JoyCard";
import { JoyChip } from "@/components/joy/JoyChip";

type Source="bloomsuite-pos"|"ideal-api"|"ideal-import"|"connected-pos";
type Result={report_type?:string;source_rows?:number;accepted?:number;duplicates?:number;rejected?:number;customers_touched?:number;duplicate_file?:boolean;message?:string;errors?:string[]};
const sources=[
 {id:"bloomsuite-pos" as Source,title:"BloomSuite POS",badge:"Best experience",icon:Sparkles,copy:"Native, real-time customer and transaction intelligence with no separate data sync."},
 {id:"connected-pos" as Source,title:"Connected POS",badge:"Automatic",icon:PlugZap,copy:"Use an existing Square, Shopify, Lightspeed, or other supported BloomSuite POS connection."},
 {id:"ideal-api" as Source,title:"Ideal API",badge:"Preferred for Ideal",icon:Database,copy:"Use Ideal's partner API when your Ideal account has API access. BloomSuite can then keep intelligence current automatically."},
 {id:"ideal-import" as Source,title:"Ideal report sync",badge:"Works today",icon:FileSpreadsheet,copy:"Securely process Ideal customer, sales, points, and coupon reports using BloomSuite's duplicate-proof import framework."},
];

export function CustomerIntelligenceSetupWizard(){
 const navigate=useNavigate();const [source,setSource]=React.useState<Source>("bloomsuite-pos");const [step,setStep]=React.useState(0);
 const [files,setFiles]=React.useState<File[]>([]);const [results,setResults]=React.useState<Result[]>([]);const [uploading,setUploading]=React.useState(false);
 const next=()=>setStep(v=>Math.min(3,v+1));
 const upload=async()=>{
  if(!files.length){toast.error("Choose at least one Ideal report.");return;}
  setUploading(true);const nextResults:Result[]=[];
  try{for(const file of files){const form=new FormData();form.append("file",file);const {data,error}=await supabase.functions.invoke("ideal-intelligence-import",{body:form});if(error)throw error;nextResults.push(data as Result);}setResults(nextResults);setStep(2);toast.success("Ideal reports processed and reconciled.");}
  catch(e){toast.error(e instanceof Error?e.message:"Ideal report import failed.");}finally{setUploading(false);}
 };
 return <Stack spacing={2.5}>
  <Stack spacing=.75}><JoyChip variant="soft" color="primary" size="sm" startDecorator={<Sparkles size={13}/>}>Customer Intelligence setup</JoyChip><Typography level="h2">Turn your POS data into something useful.</Typography><Typography level="body-md" color="neutral">Choose where purchase data comes from. BloomSuite uses the same Customer Intelligence engine regardless of source, so you can change POS systems later without rebuilding your customer history.</Typography></Stack>
  <LinearProgress determinate value={(step+1)*25} sx={{borderRadius:999}}/>
  {step===0?<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:1.5}}>{sources.map(item=>{const Icon=item.icon,active=source===item.id;return <JoyCard key={item.id} interactive onClick={()=>setSource(item.id)} sx={{borderColor:active?"primary.400":"neutral.200",boxShadow:active?"var(--joy-shadow-md)":"var(--joy-shadow-sm)"}}><JoyCardContent sx={{pt:{xs:3,md:3}}}><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between"><Sheet variant="soft" color="primary" sx={{width:40,height:40,borderRadius:"lg",display:"grid",placeItems:"center"}}><Icon size={19}/></Sheet>{active?<JoyChip size="sm" color="success" startDecorator={<Check size={12}/>}>Selected</JoyChip>:<JoyChip size="sm" variant="soft">{item.badge}</JoyChip>}</Stack><Stack spacing=.5><Typography level="title-md">{item.title}</Typography><Typography level="body-sm" color="neutral">{item.copy}</Typography></Stack></Stack></JoyCardContent></JoyCard>})}</Box>:null}
  {step===1?<JoyCard variant="outlined"><JoyCardHeader title={source==="ideal-api"?"Ideal API access":source==="ideal-import"?"Upload Ideal reports":"Use your existing connection"} description={source==="ideal-api"?"API activation remains capability-gated until Ideal provides account credentials and confirms the required endpoints.":source==="ideal-import"?"Upload one or more Ideal exports. BloomSuite detects the report family, safely matches customers, prevents duplicate rows, and shows reconciliation before activation.":"BloomSuite uses your existing normalized POS customer and order data."}/><JoyCardContent>{source==="ideal-import"?<Stack spacing={2}><Sheet variant="soft" color="neutral" sx={{borderRadius:"xl",p:2.5}}><Stack spacing={1}>{["Customer Sales","Customer Sales by Sales Category","Customer Spending","Customer Points","Coupons Issued","Coupons Redeemed"].map(x=><Stack key={x} direction="row" spacing={1} alignItems="center"><Check size={14}/><Typography level="body-sm">{x}</Typography></Stack>)}</Stack></Sheet><JoyButton component="label" variant="soft" startDecorator={<UploadCloud size={15}/>}>Choose Ideal files<input hidden type="file" multiple accept=".xlsx,.xls,.csv,.txt" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></JoyButton>{files.length?<Typography level="body-sm">{files.length} file{files.length===1?"":"s"} ready: {files.map(f=>f.name).join(", ")}</Typography>:null}</Stack>:<Sheet variant="soft" color="neutral" sx={{borderRadius:"xl",p:2.5}}><Typography level="body-sm">We validate the source, match customer identities, normalize purchase events, and show health before Customer Intelligence is activated.</Typography></Sheet>}</JoyCardContent></JoyCard>:null}
  {step===2?<JoyCard variant="outlined"><JoyCardHeader title="Validated & reconciled" description="BloomSuite never silently inflates customer value. Repeat files and repeat rows are explicitly identified."/><JoyCardContent>{results.length?<Stack spacing={1.25}>{results.map((r,i)=><Sheet key={i} variant="soft" color={r.rejected?"warning":"success"} sx={{borderRadius:"xl",p:2}}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Stack><Typography level="title-sm">{r.report_type?.replaceAll("_"," ")||"Ideal report"}</Typography><Typography level="body-xs" color="neutral">{r.duplicate_file?r.message:`${r.customers_touched??0} customers touched`}</Typography></Stack><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><JoyChip size="sm">{r.accepted??0} accepted</JoyChip><JoyChip size="sm" color="neutral">{r.duplicates??0} duplicates</JoyChip><JoyChip size="sm" color={r.rejected?"warning":"neutral"}>{r.rejected??0} rejected</JoyChip></Stack></Stack></Sheet>)}</Stack>:<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(3,1fr)"},gap:1.25}}>{[["Customer identity","Match customers safely"],["Purchase history","Deduplicate transactions"],["Intelligence health","Verify usable coverage"]].map(([a,b])=><Sheet key={a} variant="soft" color="neutral" sx={{borderRadius:"xl",p:2}}><Typography level="title-sm">{a}</Typography><Typography level="body-xs" color="neutral">{b}</Typography></Sheet>)}</Box>}</JoyCardContent></JoyCard>:null}
  {step===3?<JoyCard variant="outlined"><JoyCardHeader title="Customer Intelligence is ready" description="BloomSuite can now turn connected purchase history into customer stories, audiences, opportunities, and proactive Bloom insights."/><JoyCardContent><Stack spacing={2}><Sheet variant="soft" color="primary" sx={{borderRadius:"xl",p:2.5}}><Stack direction="row" spacing={1.5}><Sparkles size={20}/><Stack><Typography level="title-md">Bloom starts working immediately</Typography><Typography level="body-sm" color="neutral">Ask Bloom to explain behavior, rank audiences, or identify valuable customers who are slowing down.</Typography></Stack></Stack></Sheet><JoyButton onClick={()=>navigate("/crm/intelligence")}>Explore Customer Intelligence</JoyButton></Stack></JoyCardContent></JoyCard>:null}
  <Stack direction="row" justifyContent="space-between"><JoyButton variant="plain" color="neutral" disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))}>Back</JoyButton>{step===0?<JoyButton onClick={next}>Continue</JoyButton>:step===1&&source==="ideal-import"?<JoyButton loading={uploading} disabled={!files.length} onClick={()=>void upload()}>Process & reconcile</JoyButton>:step<3?<JoyButton onClick={next}>Continue</JoyButton>:null}</Stack>
 </Stack>;
}