project_id = "udldmkqwnxhdeztyqcau"

[functions.draft-merge]
verify_jwt = true

[functions.delete-user-hard]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.regenerate-content-block]
verify_jwt = true

[functions.sms-processor]
verify_jwt = true

[functions.generate-multichannel-content]
verify_jwt = false

[functions.email-domain-create]
verify_jwt = true

[functions.email-domain-verify]
verify_jwt = true

[functions.domain-sandbox-config]
verify_jwt = false

[functions.domain-connect]
verify_jwt = false

[functions.domain-connect-callback]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false

[functions.generate-company-profile]
verify_jwt = false

[functions.generate-weekly-themes]
verify_jwt = false

[functions.watchdog]
verify_jwt = false

[functions.oauth-initiate]
verify_jwt = true

[functions.oauth-callback]
verify_jwt = false

[functions.ga-report-data]
verify_jwt = true
