
import { EnhancedAppleCard } from "@/components/ui/enhanced-apple-card";
import { AppleCardHeader, AppleCardContent } from "@/components/ui/apple-card";
import { HeadlineLarge, BodyMedium } from "@/components/ui/typography";
import { Button } from "@/components/ui/button";
import { Sparkles, RefreshCw } from "lucide-react";
import { TaskItem } from "./TaskItem";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

interface CampaignContentProps {
  activeCampaign: any;
  tasks: any[];
  onTaskClick: (task: any) => void;
  onTaskUpdate: () => void;
  onRefreshContent?: () => void;
  isRefreshing?: boolean;
}

export const CampaignContent = ({ 
  activeCampaign, 
  tasks, 
  onTaskClick, 
  onTaskUpdate,
  onRefreshContent,
  isRefreshing = false
}: CampaignContentProps) => {
  const { user } = useAuth();
  
  console.log('CampaignContent: Rendering with campaign:', activeCampaign?.title);
  console.log('CampaignContent: Tasks count:', tasks.length);
  
  // Calculate progress metrics
  const tasksWithContent = tasks.filter(task => task.ai_output && task.ai_output.trim() !== '');

  return (
    <EnhancedAppleCard 
      variant="elevated" 
      surface="primary"
      hoverEffect="subtle"
      animated={true}
      data-campaign-section="true"
    >
      <AppleCardHeader className="pb-4">
        <div className="space-y-4">
          {/* Header with Title and Refresh Button */}
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-semibold text-text-primary">Your Weekly Content</h2>
            {onRefreshContent && (
              <Button
                onClick={onRefreshContent}
                disabled={isRefreshing}
                size="sm"
                variant="outline"
                className="flex items-center gap-2"
              >
                <RefreshCw className={`w-4 h-4 ${isRefreshing ? 'animate-spin' : ''}`} />
                {isRefreshing ? 'Refreshing...' : 'Refresh Content'}
              </Button>
            )}
          </div>
          
          {/* Campaign Info */}
          <div className="flex items-center gap-3 apple-slide-up">
            <div className="flex items-center justify-center w-8 h-8 bg-primary/10 rounded-lg">
              <Sparkles className="w-4 h-4 text-primary" />
            </div>
            <div>
              <HeadlineLarge className="text-text-primary text-lg">
                {activeCampaign?.title || 'Loading...'}
              </HeadlineLarge>
              {tasksWithContent.length > 0 && (
                <BodyMedium className="text-text-secondary text-sm">
                  Professional marketing content generated by AI
                </BodyMedium>
              )}
            </div>
          </div>
        </div>
      </AppleCardHeader>

      <AppleCardContent className="space-y-4">
        {/* Content Display */}
        {!activeCampaign && (
          <div className="text-center py-8 apple-slide-up">
            <BodyMedium className="text-text-secondary">
              No active campaign found.
            </BodyMedium>
          </div>
        )}

        {activeCampaign && tasks.length === 0 && (
          <div className="text-center py-8 apple-slide-up">
            <div className="flex items-center justify-center w-12 h-12 bg-blue-100 rounded-full mx-auto mb-3">
              <Sparkles className="w-6 h-6 text-blue-600 animate-pulse" />
            </div>
            <BodyMedium className="text-text-secondary mb-2">
              Generating your marketing content...
            </BodyMedium>
            <BodyMedium className="text-text-tertiary text-sm">
              Campaign: {activeCampaign?.title || 'Unknown'} 
              {activeCampaign?.id && ` (ID: ${activeCampaign.id.slice(0, 8)}...)`}
            </BodyMedium>
          </div>
        )}

        {activeCampaign && tasks.length > 0 && (
          <div className="space-y-3">
            {tasks.map((task, index) => {
              console.log('CampaignContent: Rendering task', index + 1, ':', task.id, task.post_type);
              return (
                <TaskItem
                  key={task.id}
                  task={task}
                  onClick={() => {
                    console.log('CampaignContent: Task clicked:', task.id);
                    onTaskClick(task);
                  }}
                  onTaskUpdate={onTaskUpdate}
                />
              );
            })}
          </div>
        )}
      </AppleCardContent>
    </EnhancedAppleCard>
  );
};
