import {afterAll,beforeAll,describe,expect,it,vi} from 'vitest';
import {webcrypto} from 'node:crypto';
import {explorePurchases,analyzeBasket,assertDate,finiteNumber,localDate,validatePurchaseRule,type PurchaseFact,type CustomerSet} from '../../../../supabase/functions/_shared/customer-intelligence/purchase-exploration';
import {compareCustomerGrowth,moneyMinorUnits,type GrowthOrder,type GrowthSettings} from '../../../../supabase/functions/_shared/customer-intelligence/customer-growth';
import {rankCustomerPopulation,parseScoreWeights,type RankingRow} from '../../../../supabase/functions/_shared/customer-intelligence/customer-ranking';
import {readAllPages} from '../../../../supabase/functions/_shared/customer-intelligence/query-pages';
import {customerExplorationTools} from '../../../../supabase/functions/bloom-assist/tools/customer-exploration-registry';
import {requireAnalysisAccess,exploreCustomerPurchases} from '../../../../supabase/functions/bloom-assist/tools/implementations/customer-exploration';
import type {ToolExecutionContext} from '../../../../supabase/functions/bloom-assist/tools/types';

beforeAll(()=>vi.stubGlobal('crypto',webcrypto));afterAll(()=>vi.unstubAllGlobals());
const now='2026-10-07T19:00:00Z';
const base={tenantId:'t',userId:'u',conversationId:'c',timezone:'America/Vancouver',population:['alice','bob','cara','dan'],label:'Hydrangea buyers',now};
const fact=(id:string,customer_id:string,product_name:string|null,extra:Partial<PurchaseFact>={}):PurchaseFact=>({id,customer_id,product_name,tenant_id:'t',product_code:'sku-'+id,sales_category:'Nursery',department:'Plants',quantity:1,net_amount:25,currency:'CAD',purchased_at:'2026-09-01T19:00:00Z',created_at:'2026-10-01T00:00:00Z',source:'synthetic-test',...extra});
const facts=[fact('a-h','alice','Hydrangea'),fact('a-f','alice','Fertilizer',{purchased_at:'2026-09-10T19:00:00Z'}),fact('b-h','bob','Hydrangea'),fact('b-f','bob','Fertilizer',{purchased_at:'2026-10-06T19:00:00Z'}),fact('c-h','cara',null)];
const search=(rule:Parameters<typeof explorePurchases>[0]['rule'],previous?:CustomerSet,inputFacts=facts)=>explorePurchases({...base,facts:inputFacts,rule,previous});
describe('deterministic follow-up customer exploration',()=>{
 it('finds purchase customers without inventing missing names',()=>{const s=search({mode:'purchased',product:'hydrangea'});expect(s.included_ids).toEqual(['alice','bob']);expect(s.unknown_ids).toEqual(['cara','dan']);});
 it('keeps the exact previous population for the next question',()=>{const first=search({mode:'purchased',product:'hydrangea'});const next=search({mode:'purchased',product:'fertilizer'},first,[...facts,fact('d-f','dan','Fertilizer')]);expect(next.included_ids).toEqual(['alice','bob']);expect(next.trail.at(-1)?.input).toBe(2);expect(next.parent_id).toBe(first.id);});
 it('measures elapsed days after a prior purchase',()=>{const first=search({mode:'purchased',product:'hydrangea'});const next=search({mode:'purchased',product:'fertilizer',within_days:30},first);expect(next.included_ids).toEqual(['alice']);expect(next.excluded_ids).toEqual(['bob']);});
 it('can branch from an earlier group rather than a previous answer count',()=>{const first=search({mode:'purchased',product:'hydrangea'});const narrowed=search({mode:'purchased',product:'fertilizer',within_days:30},first);expect(search({mode:'purchased',product:'fertilizer'},first).included_ids).toHaveLength(2);expect(narrowed.included_ids).toHaveLength(1);});
 it('distinguishes known non-matches from missing history',()=>{const s=search({mode:'not_purchased',product:'hydrangea'},undefined,[fact('a','alice','Rose'),fact('b','bob','Hydrangea'),fact('c','cara',null)]);expect(s.included_ids).toEqual(['alice']);expect(s.excluded_ids).toEqual(['bob']);expect(s.unknown_ids).toEqual(['cara','dan']);});
 it('can inspect everyone without hidden consent or persona filtering',()=>expect(search({mode:'all'}).included_ids).toEqual(base.population));
 it('matches exact SKU independently of a missing product name',()=>expect(search({mode:'purchased',product:'sku-c-h',product_match:'sku'}).included_ids).toEqual(['cara']));
 it('does not treat returns as new purchases',()=>expect(search({mode:'purchased',product:'Hydrangea'},undefined,[fact('a','alice','Hydrangea',{quantity:-1})]).included_ids).toEqual([]));
 it('keeps missing quantity unknown',()=>expect(search({mode:'purchased',product:'Hydrangea'},undefined,[fact('a','alice','Hydrangea',{quantity:null})]).unknown_ids).toContain('alice'));
 it('deduplicates repeated identical purchase rows',()=>expect(search({mode:'purchased',product:'Hydrangea'},undefined,[facts[0],facts[0]]).evidence_ids.alice).toEqual(['a-h']));
 it('rejects conflicting duplicate purchase identities',()=>expect(()=>search({mode:'all'},undefined,[facts[0],{...facts[0],quantity:2}])).toThrow(/Conflicting/));
 it('rejects cross-tenant facts',()=>expect(()=>search({mode:'all'},undefined,[{...facts[0],tenant_id:'other'}])).toThrow(/Cross-company/));
 it.each(['tenant_id','user_id','conversation_id'] as const)('rejects result reuse across %s',field=>{const s=search({mode:'all'});expect(()=>search({mode:'all'},{...s,[field]:'other'})).toThrow(/outside/);});
 it('rejects invisibly shrinking an old audience after access changes',()=>{const s=search({mode:'all'});expect(()=>explorePurchases({...base,population:['alice'],facts,rule:{mode:'all'},previous:s})).toThrow(/no longer accessible/);});
 it('does not count facts created after the source-read time',()=>expect(search({mode:'purchased',product:'Hydrangea'},undefined,[fact('a','alice','Hydrangea',{created_at:'2027-01-01'})]).included_ids).toEqual([]));
 it('uses local rather than UTC day boundaries',()=>{const s=search({mode:'purchased',product:'Hydrangea',start_date:'2026-09-01',end_date:'2026-09-01'},undefined,[fact('a','alice','Hydrangea',{purchased_at:'2026-09-02T01:00:00Z'})]);expect(s.included_ids).toEqual(['alice']);});
 it('counts unique customers, not units, in basket percentages',()=>{const r=analyzeBasket([...facts,facts[0]],['alice','bob'],'t');expect(r.denominator).toBe(2);expect(r.products.find(p=>p.product==='Hydrangea')).toEqual({product:'Hydrangea',customers:2,percent:100});});
 it('requires earlier dated evidence for within-days questions',()=>expect(()=>search({mode:'purchased',product:'Fertilizer',within_days:30})).toThrow(/earlier result/));
 it('rejects unknown rule fields instead of ignoring them',()=>expect(()=>validatePurchaseRule({mode:'purchased',age:20})).toThrow(/Unsupported/));
 it('rejects hidden filters on an all-customer rule',()=>expect(()=>validatePurchaseRule({mode:'all',product:'x'})).toThrow(/hidden/));
 it.each(['2026-02-30','not-a-date','2026-9-1'])('rejects invalid calendar date %s',d=>expect(()=>assertDate(d)).toThrow());
 it('rejects reversed date ranges',()=>expect(()=>validatePurchaseRule({mode:'purchased',start_date:'2026-09-05',end_date:'2026-09-01'})).toThrow());
 it('does not manufacture zero from blank and null numbers',()=>{for(const v of [null,undefined,'',true,{},'NaN','Infinity'])expect(finiteNumber(v)).toBeNull();expect(finiteNumber('0')).toBe(0);});
 it('rejects invalid time zones',()=>expect(()=>localDate(now,'Bogus/Zone')).toThrow());
});
const settings:GrowthSettings={current_start:'2026-09-01',current_end:'2026-09-30',baseline_start:'2025-09-01',baseline_end:'2025-09-30',currency:'CAD',timezone:'America/Vancouver',data_cutoff:now,spend_weight:50,visits_weight:50};
const order=(id:string,customer:string,date:string,total:number|string=50,extra:Partial<GrowthOrder>={}):GrowthOrder=>({id,tenant_id:'t',crm_customer_id:customer,order_date:date+'T19:00:00Z',created_at:'2026-10-01T00:00:00Z',total_amount:total,refund_amount:null,currency:'CAD',status:'completed',...extra});
const growth=(orders:GrowthOrder[],s=settings)=>compareCustomerGrowth(orders,['alice'],'t',s);
describe('customer-over-customer growth, not invented estimates',()=>{
 it('calculates one visit to two as 100% growth, index 200',()=>{const r=growth([order('1','alice','2025-09-01'),order('2','alice','2026-09-01'),order('3','alice','2026-09-02')]);expect(r.rows[0]).toMatchObject({growth_index:200,growth_change_percent:100,visits_change_percent:100,spend_change_percent:100,state:'retained'});});
 it('keeps no-data customers unscored',()=>expect(growth([]).rows[0]).toMatchObject({growth_index:null,state:'no_comparable_history'}));
 it('does not invent percentage growth from a zero baseline',()=>expect(growth([order('1','alice','2026-09-01')]).rows[0]).toMatchObject({growth_index:null,state:'newly_observed'}));
 it('identifies lapsed customers',()=>expect(growth([order('1','alice','2025-09-01')]).rows[0]).toMatchObject({growth_index:0,state:'lapsed'}));
 it('identifies reactivation only when earlier purchase history exists',()=>expect(growth([order('1','alice','2024-09-01'),order('2','alice','2026-09-01')]).rows[0].state).toBe('reactivated'));
 it('sums decimal currency exactly',()=>expect(growth([order('1','alice','2026-09-01','0.10'),order('2','alice','2026-09-02','0.20')]).rows[0].current_spend).toBe(.3));
 it('subtracts known partial refunds',()=>expect(growth([order('1','alice','2026-09-01',100,{refund_amount:20,status:'partially_refunded'})]).rows[0].current_spend).toBe(80));
 it('does not invent an unknown refund amount',()=>expect(growth([order('1','alice','2026-09-01',100,{status:'refunded'})]).rows[0].state).toBe('incomplete_data'));
 it('keeps invalid order values unscored',()=>expect(growth([order('1','alice','2025-09-01'),order('2','alice','2026-09-01','bad')]).rows[0].growth_index).toBeNull());
 it('ignores explicitly cancelled orders',()=>expect(growth([order('1','alice','2026-09-01',100,{status:'cancelled'})]).rows[0].current_visits).toBe(0));
 it('does not combine currencies',()=>expect(growth([order('1','alice','2026-09-01',100,{currency:'USD'})]).rows[0]).toMatchObject({current_spend:0,other_currency_rows:1}));
 it('rejects cross-company orders',()=>expect(()=>growth([order('1','alice','2026-09-01',100,{tenant_id:'other'})])).toThrow(/Cross-company/));
 it('deduplicates repeated identical orders',()=>{const o=order('1','alice','2026-09-01');expect(growth([o,o]).rows[0].current_visits).toBe(1);});
 it('rejects inconsistent versions of an order',()=>{const o=order('1','alice','2026-09-01');expect(()=>growth([o,{...o,total_amount:90}])).toThrow(/Conflicting/);});
 it('requires explicit daily normalization for different-length periods',()=>{expect(()=>growth([],{...settings,current_end:'2026-09-29'})).toThrow(/different lengths/);expect(()=>growth([],{...settings,current_end:'2026-09-29',per_day_rates:true})).not.toThrow();});
 it('rejects overlapping periods',()=>expect(()=>growth([],{...settings,baseline_end:'2026-09-01'})).toThrow(/non-overlapping/));
 it('rejects future period endpoints',()=>expect(()=>growth([],{...settings,current_end:'2027-09-30'})).toThrow());
 it('rejects zero total weight',()=>expect(()=>growth([],{...settings,spend_weight:0,visits_weight:0})).toThrow(/Weights/));
 it('never claims observed growth proves campaign causation',()=>expect(growth([]).limitations.join(' ')).toMatch(/not proof/));
 it.each(['1.234','bad','','Infinity'])('rejects invalid money %s',v=>expect(moneyMinorUnits(v)).toBeNull());
});
const ranked=(id:string,extra:Partial<RankingRow>={}):RankingRow=>({customer_id:id,lifetime_value:100,purchase_frequency:1,days_since_last_purchase:5,purchase_velocity:0,total_quantity:10,departments_shopped:1,category_spend:{Nursery:100},department_spend:{Plants:100},...extra});
describe('transparent weighted rankings',()=>{
 it('explicit weights replace rather than augment defaults',()=>expect(parseScoreWeights({overall:100})).toEqual({value:0,quantity:0,breadth:0,frequency:0,overall:100,recency:0,trend:0}));
 it('ranks ties equally and deterministically',()=>expect(rankCustomerPopulation([ranked('b'),ranked('a')],{weights:{overall:100}}).rows.map(r=>[r.customer_id,r.score])).toEqual([['a',50],['b',50]]));
 it('makes more recent customers rank higher',()=>expect(rankCustomerPopulation([ranked('old',{days_since_last_purchase:90}),ranked('new')],{weights:{recency:100}}).rows[0].customer_id).toBe('new'));
 it('shows missing factors instead of treating them as zero',()=>expect(rankCustomerPopulation([ranked('a',{lifetime_value:null}),ranked('b')],{weights:{overall:100}}).unranked).toEqual([{customer_id:'a',missing_factors:['overall']}])) ;
 it('permits irrelevant missing fields when their weight is zero',()=>expect(rankCustomerPopulation([ranked('a',{purchase_frequency:null})],{weights:{overall:100}}).eligible_customers).toBe(1));
 it('reports customers outside the selected top-N',()=>expect(rankCustomerPopulation([ranked('a'),ranked('b')],{limit:1}).omitted_by_limit).toBe(1));
 it('reports missing category history as unknown',()=>expect(rankCustomerPopulation([ranked('a',{category_spend:{}})],{dimension:'category',dimension_value:'Nursery',weights:{value:100}}).unranked).toHaveLength(1));
 it.each([{secret:100},{overall:-1},{overall:0},{overall:'100'}])('rejects invalid weights %j',weights=>expect(()=>parseScoreWeights(weights)).toThrow());
 it('exposes the source values for every score',()=>expect(rankCustomerPopulation([ranked('a')]).rows[0]).toHaveProperty('source_values.overall',100));
});
describe('complete queries and permission checks',()=>{
 it('reads beyond default API limits',async()=>{const all=Array.from({length:6123},(_,id)=>id);const result=await readAllPages(async(a,b)=>({data:all.slice(a,b+1),error:null}));expect(result).toHaveLength(6123);});
 it('fails rather than reporting a partial population',async()=>await expect(readAllPages(async()=>({data:Array(1000).fill(1),error:null}),1500)).rejects.toThrow(/partial/));
 it('propagates API errors',async()=>await expect(readAllPages(async()=>({data:null,error:{message:'Permission denied'}}))).rejects.toThrow('Permission denied'));
 it('does not fall back to a service client for customer reads',async()=>await expect(requireAnalysisAccess({tenantId:'t',userId:'u',serviceClient:{}} as ToolExecutionContext)).rejects.toThrow(/authenticated/));
 it('requires both customer and report permissions',async()=>{const rpc=vi.fn().mockResolvedValueOnce({data:true,error:null}).mockResolvedValueOnce({data:false,error:null});await expect(requireAnalysisAccess({tenantId:'t',userId:'u',dataClient:{rpc}} as unknown as ToolExecutionContext)).rejects.toThrow(/reporting/);expect(rpc).toHaveBeenCalledTimes(2);});
 it('checks tenant context before running a query',async()=>await expect(requireAnalysisAccess({tenantId:'t',authenticatedTenantId:'other',userId:'u',dataClient:{}} as ToolExecutionContext)).rejects.toThrow());
 it('requires a scope, so a follow-up cannot silently search everyone',async()=>await expect(exploreCustomerPurchases({criteria:{mode:'all'}},{} as ToolExecutionContext)).rejects.toThrow(/starting population/));
 it('makes only the save action a confirmation-required mutation',()=>{expect(customerExplorationTools.filter(t=>t.requires_confirmation).map(t=>t.function.name)).toEqual(['save_customer_set_segment']);});
});

describe('Bloom can actually discover the new tools',()=>{
 it('exposes read-only exploration to query intent, not just analytics intent',()=>expect(customerExplorationTools.filter(t=>!t.requires_confirmation).every(t=>t.category==='query')).toBe(true));
});
