import type { Json } from "@/integrations/supabase/types";

export const BLOOM_TASK_PLAN_BLOCK_TYPE = "task_plan";

export type BloomTaskPlanAction =
  | "create"
  | "update"
  | "delete"
  | "send"
  | "schedule"
  | "assign"
  | "tag"
  | "consent_change";

export type BloomTaskPlanEntityType =
  | "customer"
  | "product"
  | "campaign"
  | "segment"
  | "tag";

export type BloomTaskPlanStatus =
  | "pending"
  | "approved"
  | "skipped"
  | "executing"
  | "completed"
  | "failed"
  | "blocked";

export type BloomTaskRiskLevel = "safe" | "low" | "medium" | "high";

export type BloomValidationAnnotationType =
  | "warning"
  | "error"
  | "suggestion"
  | "info";

export type BloomTaskJsonObject = { [key: string]: Json | undefined };

export interface BloomFieldChange {
  field: string;
  currentValue: Json | null;
  newValue: Json | null;
}

export type BloomEditableFieldInputType = "text" | "textarea" | "select";

export interface BloomEditableFieldOption {
  id: string;
  label: string;
  value: Json | null;
  description: string | null;
}

export interface BloomEditableFieldMetadata {
  field: string;
  inputType: BloomEditableFieldInputType;
  label: string | null;
  autoGenerated: boolean;
  source: string | null;
  options: BloomEditableFieldOption[];
}

export interface BloomValidationAnnotation {
  type: BloomValidationAnnotationType;
  message: string;
  step: string;
}

export interface BloomTaskPlanItem {
  taskId: string;
  action: BloomTaskPlanAction;
  entityType: BloomTaskPlanEntityType;
  entityId: string | null;
  entityName: string;
  toolName: string;
  toolParams: BloomTaskJsonObject;
  description: string;
  fieldChanges: BloomFieldChange[];
  riskLevel: BloomTaskRiskLevel;
  dependsOn: string[];
  editableFields: string[];
  editableFieldMetadata: BloomEditableFieldMetadata[];
  validationAnnotations: BloomValidationAnnotation[];
  status: BloomTaskPlanStatus;
  errorMessage: string | null;
}

export interface BloomCompactConfirmation {
  entityName: string;
  fieldName: string;
  currentValue: Json | null;
  newValue: Json | null;
}

export interface BloomTaskPlan {
  planId: string;
  originatingMessageId: string;
  summary: string;
  riskLevel: BloomTaskRiskLevel;
  compact: boolean;
  compactConfirmation: BloomCompactConfirmation | null;
  tasks: BloomTaskPlanItem[];
  createdAt: string;
}

export interface BloomTaskStatusUpdate {
  planId: string;
  taskId: string;
  status: BloomTaskPlanStatus;
  errorMessage: string | null;
}

export interface BloomTaskCompletionSummary {
  planId: string;
  completed: number;
  skipped: number;
  failed: number;
  blocked: number;
}

export type BloomEditedTaskFields = Record<string, BloomTaskJsonObject>;

const TASK_ACTIONS = new Set<BloomTaskPlanAction>([
  "create",
  "update",
  "delete",
  "send",
  "schedule",
  "assign",
  "tag",
  "consent_change",
]);

const ENTITY_TYPES = new Set<BloomTaskPlanEntityType>([
  "customer",
  "product",
  "campaign",
  "segment",
  "tag",
]);

const TASK_STATUSES = new Set<BloomTaskPlanStatus>([
  "pending",
  "approved",
  "skipped",
  "executing",
  "completed",
  "failed",
  "blocked",
]);

const RISK_LEVELS = new Set<BloomTaskRiskLevel>([
  "safe",
  "low",
  "medium",
  "high",
]);

const ANNOTATION_TYPES = new Set<BloomValidationAnnotationType>([
  "warning",
  "error",
  "suggestion",
  "info",
]);

export const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

export const isJsonValue = (value: unknown): value is Json => {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return true;
  }

  if (Array.isArray(value)) {
    return value.every(isJsonValue);
  }

  if (!isRecord(value)) {
    return false;
  }

  return Object.values(value).every(
    (entry) => entry === undefined || isJsonValue(entry),
  );
};

const readString = (value: unknown): string | null =>
  typeof value === "string" && value.trim() ? value.trim() : null;

const readBoolean = (value: unknown): boolean | null =>
  typeof value === "boolean" ? value : null;

const readNumber = (value: unknown): number | null =>
  typeof value === "number" && Number.isFinite(value) ? value : null;

const readStringArray = (value: unknown): string[] =>
  Array.isArray(value)
    ? value.filter(
        (entry): entry is string =>
          typeof entry === "string" && entry.trim().length > 0,
      )
    : [];

const readJsonObject = (value: unknown): BloomTaskJsonObject => {
  if (!isRecord(value)) {
    return {};
  }

  const output: BloomTaskJsonObject = {};
  for (const [key, entry] of Object.entries(value)) {
    if (entry === undefined || isJsonValue(entry)) {
      output[key] = entry;
    }
  }
  return output;
};

const readRiskLevel = (value: unknown): BloomTaskRiskLevel | null =>
  typeof value === "string" && RISK_LEVELS.has(value as BloomTaskRiskLevel)
    ? (value as BloomTaskRiskLevel)
    : null;

const readStatus = (value: unknown): BloomTaskPlanStatus | null =>
  typeof value === "string" && TASK_STATUSES.has(value as BloomTaskPlanStatus)
    ? (value as BloomTaskPlanStatus)
    : null;

const readAction = (value: unknown): BloomTaskPlanAction | null =>
  typeof value === "string" && TASK_ACTIONS.has(value as BloomTaskPlanAction)
    ? (value as BloomTaskPlanAction)
    : null;

const readEntityType = (value: unknown): BloomTaskPlanEntityType | null =>
  typeof value === "string" &&
  ENTITY_TYPES.has(value as BloomTaskPlanEntityType)
    ? (value as BloomTaskPlanEntityType)
    : null;

const readAnnotationType = (
  value: unknown,
): BloomValidationAnnotationType | null =>
  typeof value === "string" &&
  ANNOTATION_TYPES.has(value as BloomValidationAnnotationType)
    ? (value as BloomValidationAnnotationType)
    : null;

const parseFieldChange = (value: unknown): BloomFieldChange | null => {
  if (!isRecord(value)) {
    return null;
  }

  const field = readString(value.field);
  if (!field) {
    return null;
  }

  return {
    field,
    currentValue: isJsonValue(value.current_value) ? value.current_value : null,
    newValue: isJsonValue(value.new_value) ? value.new_value : null,
  };
};

const readEditableFieldInputType = (
  value: unknown,
): BloomEditableFieldInputType => {
  if (value === "textarea" || value === "select" || value === "text") {
    return value;
  }
  return "text";
};

const parseEditableFieldOption = (
  value: unknown,
  index: number,
): BloomEditableFieldOption | null => {
  if (!isRecord(value)) {
    const label = readString(value);
    return label
      ? { id: `option-${index + 1}`, label, value: label, description: null }
      : null;
  }

  const label = readString(value.label) ?? readString(value.value);
  if (!label) {
    return null;
  }

  return {
    id: readString(value.id) ?? `option-${index + 1}`,
    label,
    value: isJsonValue(value.value) ? value.value : label,
    description: readString(value.description),
  };
};

const parseEditableFieldMetadata = (
  value: unknown,
): BloomEditableFieldMetadata | null => {
  if (!isRecord(value)) {
    return null;
  }

  const field = readString(value.field);
  if (!field) {
    return null;
  }

  const options = Array.isArray(value.options)
    ? value.options
        .map(parseEditableFieldOption)
        .filter((entry): entry is BloomEditableFieldOption => entry !== null)
    : [];

  return {
    field,
    inputType: readEditableFieldInputType(value.input_type ?? value.inputType),
    label: readString(value.label),
    autoGenerated:
      readBoolean(value.auto_generated ?? value.autoGenerated) ?? false,
    source: readString(value.source),
    options,
  };
};

const parseAnnotation = (value: unknown): BloomValidationAnnotation | null => {
  if (!isRecord(value)) {
    return null;
  }

  const type = readAnnotationType(value.type);
  const message = readString(value.message);
  const step = readString(value.step) ?? "validation";
  if (!type || !message) {
    return null;
  }

  return { type, message, step };
};

const parseCompactConfirmation = (
  value: unknown,
): BloomCompactConfirmation | null => {
  if (!isRecord(value)) {
    return null;
  }

  const entityName = readString(value.entity_name);
  const fieldName = readString(value.field_name);
  if (!entityName || !fieldName) {
    return null;
  }

  return {
    entityName,
    fieldName,
    currentValue: isJsonValue(value.current_value) ? value.current_value : null,
    newValue: isJsonValue(value.new_value) ? value.new_value : null,
  };
};

const parseTask = (value: unknown): BloomTaskPlanItem | null => {
  if (!isRecord(value)) {
    return null;
  }

  const taskId = readString(value.task_id);
  const action = readAction(value.action);
  const entityType = readEntityType(value.entity_type);
  const entityName = readString(value.entity_name);
  const toolName = readString(value.tool_name);
  const description = readString(value.description);
  const riskLevel = readRiskLevel(value.risk_level);
  const status = readStatus(value.status);

  if (
    !taskId ||
    !action ||
    !entityType ||
    !entityName ||
    !toolName ||
    !description ||
    !riskLevel ||
    !status
  ) {
    return null;
  }

  const fieldChanges = Array.isArray(value.field_changes)
    ? value.field_changes
        .map(parseFieldChange)
        .filter((entry): entry is BloomFieldChange => entry !== null)
    : [];
  const validationAnnotations = Array.isArray(value.validation_annotations)
    ? value.validation_annotations
        .map(parseAnnotation)
        .filter((entry): entry is BloomValidationAnnotation => entry !== null)
    : [];
  const editableFieldMetadata = Array.isArray(value.editable_field_metadata)
    ? value.editable_field_metadata
        .map(parseEditableFieldMetadata)
        .filter((entry): entry is BloomEditableFieldMetadata => entry !== null)
    : [];

  return {
    taskId,
    action,
    entityType,
    entityId: readString(value.entity_id),
    entityName,
    toolName,
    toolParams: readJsonObject(value.tool_params),
    description,
    fieldChanges,
    riskLevel,
    dependsOn: readStringArray(value.depends_on),
    editableFields: readStringArray(value.editable_fields),
    editableFieldMetadata,
    validationAnnotations,
    status,
    errorMessage: readString(value.error_message),
  };
};

export const parseBloomTaskPlan = (value: unknown): BloomTaskPlan | null => {
  const source =
    isRecord(value) && value.block_type === BLOOM_TASK_PLAN_BLOCK_TYPE
      ? value.task_plan
      : value;

  if (!isRecord(source)) {
    return null;
  }

  const planId = readString(source.plan_id);
  const originatingMessageId = readString(source.originating_message_id);
  const summary = readString(source.summary) ?? "Task execution plan";
  const riskLevel = readRiskLevel(source.risk_level);
  const compact = readBoolean(source.compact) ?? false;
  const createdAt = readString(source.created_at);
  const tasks = Array.isArray(source.tasks)
    ? source.tasks
        .map(parseTask)
        .filter((task): task is BloomTaskPlanItem => task !== null)
    : [];

  if (
    !planId ||
    !originatingMessageId ||
    !riskLevel ||
    !createdAt ||
    tasks.length === 0
  ) {
    return null;
  }

  return {
    planId,
    originatingMessageId,
    summary,
    riskLevel,
    compact,
    compactConfirmation: parseCompactConfirmation(source.compact_confirmation),
    tasks,
    createdAt,
  };
};

export const parseBloomTaskStatusUpdate = (
  value: unknown,
): BloomTaskStatusUpdate | null => {
  if (!isRecord(value)) {
    return null;
  }

  const planId = readString(value.plan_id);
  const taskId = readString(value.task_id);
  const status = readStatus(value.status);
  if (!planId || !taskId || !status) {
    return null;
  }

  return {
    planId,
    taskId,
    status,
    errorMessage: readString(value.error_message),
  };
};

export const parseBloomTaskCompletionSummary = (
  value: unknown,
): BloomTaskCompletionSummary | null => {
  if (!isRecord(value)) {
    return null;
  }

  const planId = readString(value.plan_id);
  const completed = readNumber(value.completed_count);
  const skipped = readNumber(value.skipped_count);
  const failed = readNumber(value.failed_count);
  const blocked = readNumber(value.blocked_count);
  if (
    !planId ||
    completed === null ||
    skipped === null ||
    failed === null ||
    blocked === null
  ) {
    return null;
  }

  return { planId, completed, skipped, failed, blocked };
};

export const taskPlanBlockData = (plan: BloomTaskPlan): Json => ({
  block_type: BLOOM_TASK_PLAN_BLOCK_TYPE,
  task_plan: {
    plan_id: plan.planId,
    originating_message_id: plan.originatingMessageId,
    summary: plan.summary,
    risk_level: plan.riskLevel,
    compact: plan.compact,
    compact_confirmation: plan.compactConfirmation
      ? {
          entity_name: plan.compactConfirmation.entityName,
          field_name: plan.compactConfirmation.fieldName,
          current_value: plan.compactConfirmation.currentValue,
          new_value: plan.compactConfirmation.newValue,
        }
      : null,
    tasks: plan.tasks.map((task) => ({
      task_id: task.taskId,
      action: task.action,
      entity_type: task.entityType,
      entity_id: task.entityId,
      entity_name: task.entityName,
      tool_name: task.toolName,
      tool_params: task.toolParams,
      description: task.description,
      field_changes: task.fieldChanges.map((fieldChange) => ({
        field: fieldChange.field,
        current_value: fieldChange.currentValue,
        new_value: fieldChange.newValue,
      })),
      risk_level: task.riskLevel,
      depends_on: task.dependsOn,
      editable_fields: task.editableFields,
      editable_field_metadata: task.editableFieldMetadata.map((metadata) => ({
        field: metadata.field,
        input_type: metadata.inputType,
        label: metadata.label,
        auto_generated: metadata.autoGenerated,
        source: metadata.source,
        options: metadata.options.map((option) => ({
          id: option.id,
          label: option.label,
          value: option.value,
          description: option.description,
        })),
      })),
      validation_annotations: task.validationAnnotations.map((annotation) => ({
        type: annotation.type,
        message: annotation.message,
        step: annotation.step,
        resolution_options: [],
      })),
      status: task.status,
      error_message: task.errorMessage,
    })),
    created_at: plan.createdAt,
  },
});
