import React, { useState, useEffect } from "react";
import { showToast } from "@/utils/toastUtils";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useTenant } from "@/hooks/useTenant";
import { ContentViewerDialog } from "./ContentViewerDialog";
import { useContentGeneration } from "./ContentGenerationLogic";

interface ContentViewerProps {
  campaignId: string;
  campaignTitle: string;
  isOpen: boolean;
  onClose: () => void;
  onTaskUpdate?: () => void;
}

export const ContentViewer = ({
  campaignId,
  campaignTitle,
  isOpen,
  onClose,
  onTaskUpdate,
}: ContentViewerProps) => {
  const { user } = useAuth();
  const { tenant } = useTenant();
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const { generateMissingContent } = useContentGeneration();

  const fetchTasks = async () => {
    if (!campaignId || !isOpen || !user) {
      return;
    }
    setLoading(true);

    try {
      // SECURITY FIX: First verify the campaign belongs to the current user/tenant
      let campaignQuery = supabase
        .from("campaigns")
        .select("user_id, tenant_id")
        .eq("id", campaignId);

      if (tenant?.id) {
        campaignQuery = campaignQuery.eq("tenant_id", tenant.id);
      } else {
        campaignQuery = campaignQuery.eq("user_id", user.id);
      }

      const { data: campaignData, error: campaignError } =
        await campaignQuery.single();

      if (campaignError || !campaignData) {
        console.error(
          "ContentViewer: Campaign not found or not owned by user/tenant:",
          campaignError,
        );
        toast.error(
          "Access denied: Campaign not found or you do not have permission to view it",
        );
        setTasks([]);
        return;
      }

      // Now fetch tasks for the verified campaign with tenant-aware query
      let tasksQuery = supabase
        .from("content_tasks")
        .select(
          `
          *,
          campaigns!inner (
            title,
            user_id,
            tenant_id
          )
        `,
        )
        .eq("campaign_id", campaignId)
        .order("created_at", { ascending: true });

      if (tenant?.id) {
        // Tenant-based access control
        tasksQuery = tasksQuery.eq("campaigns.tenant_id", tenant.id);
      } else {
        // User-based access control
        tasksQuery = tasksQuery.eq("campaigns.user_id", user.id);
      }

      const { data, error } = await tasksQuery;
      if (error) {
        console.error("ContentViewer: Error fetching tasks:", error);
        toast.error(`Failed to load content: ${error.message}`);
        setTasks([]);
      } else {
        // Additional security verification
        const userTasks =
          data?.filter(
            (task) =>
              task.campaigns &&
              (tenant?.id
                ? task.campaigns.tenant_id === tenant.id
                : task.campaigns.user_id === user.id),
          ) || [];

        if (userTasks.length !== data?.length) {
        }

        // Log detailed task status for debugging
        if (userTasks.length > 0) {
          userTasks.forEach((task) => {
            const hasContent = task.ai_output && task.ai_output.trim() !== "";
          });
        }

        setTasks(userTasks);

        // Check if we have content or if we need to auto-generate
        const tasksWithContent = userTasks.filter(
          (task) => task.ai_output && task.ai_output.trim() !== "",
        );
        const tasksNeedingContent = userTasks.filter(
          (task) => !task.ai_output || task.ai_output.trim() === "",
        );

        // Auto-generate missing content if this is the first load and there are tasks without content
        if (!hasAutoGenerated && tasksNeedingContent.length > 0) {
          setHasAutoGenerated(true); // Set this first to prevent multiple calls

          try {
            const success = await generateMissingContent(
              campaignId,
              campaignTitle,
              user.id,
            );
            if (success && onTaskUpdate) {
              onTaskUpdate();
              // Refetch tasks after generation
              setTimeout(() => {
                fetchTasks();
              }, 3000); // Give more time for generation to complete
            }
          } catch (autoGenError) {
            console.error(
              "ContentViewer: Auto-generation failed:",
              autoGenError,
            );
            toast.error(
              "Failed to auto-generate content. You can try generating manually.",
            );
            setHasAutoGenerated(false); // Reset so user can retry
          }
        } else if (tasksNeedingContent.length === 0) {
        } else if (hasAutoGenerated) {
        }
      }
    } catch (error) {
      console.error("ContentViewer: Exception in fetchTasks:", error);
      toast.error("An unexpected error occurred loading content");
      setTasks([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen && campaignId && user) {
      // Only reset auto-generation flag when opening a different campaign
      fetchTasks();
    } else if (!isOpen) {
      // Reset state when dialog closes
      setTasks([]);
      setHasAutoGenerated(false);
    }
  }, [campaignId, isOpen, user, tenant]);

  const handleTaskUpdate = () => {
    fetchTasks();
    if (onTaskUpdate) onTaskUpdate();
  };

  const handleManualGeneration = async () => {
    if (!user) {
      toast.error("Please log in to generate content");
      return;
    }
    setLoading(true);

    try {
      const success = await generateMissingContent(
        campaignId,
        campaignTitle,
        user.id,
      );
      if (success) {
        toast.success("Content generation started");
        handleTaskUpdate();
      }
    } catch (error) {
      console.error("ContentViewer: Manual generation failed:", error);
      toast.error("Failed to generate content");
    } finally {
      setLoading(false);
    }
  };

  // Don't render if no authenticated user
  if (!user) {
    return null;
  }

  return (
    <ContentViewerDialog
      isOpen={isOpen}
      onClose={onClose}
      campaignTitle={campaignTitle}
      loading={loading}
      tasks={tasks}
      onTaskUpdate={handleTaskUpdate}
      onManualGeneration={handleManualGeneration}
    />
  );
};
