
import React, { useState, useEffect } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { ContentViewerDialog } from "./ContentViewerDialog";
import { useContentGeneration } from "./ContentGenerationLogic";

interface ContentViewerProps {
  campaignId: string;
  campaignTitle: string;
  isOpen: boolean;
  onClose: () => void;
  onTaskUpdate?: () => void;
}

export const ContentViewer = ({ campaignId, campaignTitle, isOpen, onClose, onTaskUpdate }: ContentViewerProps) => {
  const { user } = useAuth();
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const { autoGenerateAllContent } = useContentGeneration();

  const fetchTasks = async () => {
    if (!campaignId || !isOpen) {
      console.log('ContentViewer: Skipping fetch - campaignId:', campaignId, 'isOpen:', isOpen);
      return;
    }
    
    console.log('ContentViewer: Starting fetch for campaignId:', campaignId);
    setLoading(true);
    
    try {
      const { data, error } = await supabase
        .from('content_tasks')
        .select('*')
        .eq('campaign_id', campaignId)
        .order('created_at', { ascending: true });

      console.log('ContentViewer: Fetch result - data:', data, 'error:', error);

      if (error) {
        console.error('ContentViewer: Error fetching tasks:', error);
        toast.error(`Failed to load content: ${error.message}`);
      } else {
        console.log('ContentViewer: Successfully fetched', data?.length || 0, 'tasks');
        setTasks(data || []);
        
        // Auto-generate missing content if this is the first load
        if (!hasAutoGenerated && (data?.length === 0 || data?.some(task => !task.ai_output))) {
          if (user) {
            console.log('ContentViewer: Auto-generating missing content');
            try {
              const success = await autoGenerateAllContent(campaignId, campaignTitle, data || [], user.id);
              if (success && onTaskUpdate) onTaskUpdate();
            } catch (autoGenError) {
              console.error('ContentViewer: Auto-generation failed:', autoGenError);
              toast.error('Failed to auto-generate content. You can try generating manually.');
            }
          }
          setHasAutoGenerated(true);
        }
      }
    } catch (error) {
      console.error('ContentViewer: Exception in fetchTasks:', error);
      toast.error('An unexpected error occurred loading content');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    console.log('ContentViewer: useEffect triggered - campaignId:', campaignId, 'isOpen:', isOpen);
    if (isOpen) {
      setHasAutoGenerated(false); // Reset for new sessions
      fetchTasks();
    }
  }, [campaignId, isOpen]);

  const handleTaskUpdate = () => {
    console.log('ContentViewer: Task update requested');
    fetchTasks();
    if (onTaskUpdate) onTaskUpdate();
  };

  return (
    <ContentViewerDialog
      isOpen={isOpen}
      onClose={onClose}
      campaignTitle={campaignTitle}
      loading={loading}
      tasks={tasks}
      onTaskUpdate={handleTaskUpdate}
    />
  );
};
