import Box from "@mui/joy/Box";
import Divider from "@mui/joy/Divider";
import Stack from "@mui/joy/Stack";
import Typography from "@mui/joy/Typography";
import { Clipboard, Copy, Sparkles, WandSparkles } from "lucide-react";
import { toast } from "sonner";
import { JoyButton } from "@/components/joy/JoyButton";
import { JoyCard } from "@/components/joy/JoyCard";
import { JoyChip } from "@/components/joy/JoyChip";
import {
  formatLabel,
  isRecord,
  readBoolean,
  readNumber,
  readString,
} from "@/components/bloom/blocks/blockUtils";

export type ContentBlockType =
  | "email_body"
  | "subject_lines"
  | "sms"
  | "product_description"
  | "social_post";

export interface ContentBlockProps {
  contentType: ContentBlockType;
  content: string | string[];
  autoGenerated?: boolean;
  characterLimit?: number | null;
  onAction: (prompt: string) => void;
}

const CONTENT_TYPE_LABELS: Record<ContentBlockType, string> = {
  email_body: "AI-generated email draft",
  product_description: "Product description",
  sms: "SMS draft",
  social_post: "Social post",
  subject_lines: "subject line options",
};

function normalizeContentType(value: unknown): ContentBlockType | null {
  const contentType = readString(value)?.toLowerCase();
  switch (contentType) {
    case "email_body":
    case "subject_lines":
    case "sms":
    case "product_description":
    case "social_post":
      return contentType;
    case "email_subject":
      return "subject_lines";
    case "sms_message":
      return "sms";
    case "campaign_copy":
      return "email_body";
    case "social_caption":
      return "social_post";
    default:
      return null;
  }
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.map(readString).filter((entry): entry is string => Boolean(entry))
    : [];
}

function stripNumberPrefix(value: string): string {
  return value.replace(/^\d+[.)]\s*/, "").trim();
}

function contentOptions(
  source: Record<string, unknown>,
  data: Record<string, unknown> | null,
): string[] {
  const direct = stringArray(source.content);
  if (direct.length > 0) {
    return direct;
  }

  const options =
    stringArray(source.options).length > 0
      ? stringArray(source.options)
      : stringArray(data?.options);
  if (options.length > 0) {
    return options;
  }

  const numbered =
    stringArray(source.numbered_options).length > 0
      ? stringArray(source.numbered_options)
      : stringArray(data?.numbered_options);
  if (numbered.length > 0) {
    return numbered.map(stripNumberPrefix).filter(Boolean);
  }

  return [];
}

function contentText(
  source: Record<string, unknown>,
  data: Record<string, unknown> | null,
): string | null {
  return (
    readString(source.content) ??
    readString(source.text) ??
    readString(source.markdown) ??
    readString(data?.text) ??
    readString(data?.content) ??
    readString(data?.markdown)
  );
}

export function normalizeContentPayload(
  payload: unknown,
): Omit<ContentBlockProps, "onAction"> | null {
  const source = isRecord(payload) ? payload : {};
  const data = isRecord(source.data) ? source.data : null;
  const contentType = normalizeContentType(
    source.contentType ??
      source.content_type ??
      data?.contentType ??
      data?.content_type,
  );

  if (!contentType) {
    return null;
  }

  if (contentType === "subject_lines") {
    const options = contentOptions(source, data);
    if (options.length === 0) {
      return null;
    }

    return {
      contentType,
      content: options,
      autoGenerated:
        readBoolean(source.autoGenerated) ??
        readBoolean(source.auto_generated) ??
        true,
      characterLimit: null,
    };
  }

  const text = contentText(source, data);
  if (!text) {
    return null;
  }

  const characterLimit =
    readNumber(source.character_limit) ??
    readNumber(data?.character_limit) ??
    (contentType === "sms" ? (text.length > 160 ? 320 : 160) : null);

  return {
    contentType,
    content: text,
    autoGenerated:
      readBoolean(source.autoGenerated) ??
      readBoolean(source.auto_generated) ??
      true,
    characterLimit,
  };
}

async function copyToClipboard(value: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(value);
    toast.success("Copied to clipboard");
  } catch {
    toast.error("Unable to copy to clipboard");
  }
}

function Header({
  autoGenerated,
  title,
}: {
  autoGenerated: boolean;
  title: string;
}) {
  return (
    <Stack
      direction="row"
      spacing={1}
      alignItems="center"
      justifyContent="space-between"
      useFlexGap
      sx={{ flexWrap: "wrap" }}
    >
      <Typography
        level="title-sm"
        sx={{ color: "neutral.900", overflowWrap: "anywhere" }}
      >
        {title}
      </Typography>
      {autoGenerated ? (
        <JoyChip
          color="primary"
          size="sm"
          variant="soft"
          startDecorator={<Sparkles size={13} strokeWidth={1.9} />}
        >
          AI-generated
        </JoyChip>
      ) : null}
    </Stack>
  );
}

function SubjectLineOptions({
  autoGenerated,
  content,
  onAction,
}: {
  autoGenerated: boolean;
  content: string[];
  onAction: (prompt: string) => void;
}) {
  return (
    <JoyCard variant="outlined" sx={{ p: 1.5, width: "100%" }}>
      <Stack spacing={1.25}>
        <Header
          autoGenerated={autoGenerated}
          title={`${content.length} ${CONTENT_TYPE_LABELS.subject_lines}`}
        />
        <Stack spacing={1}>
          {content.map((option, index) => (
            <Stack
              key={`${option}-${index}`}
              direction={{ xs: "column", sm: "row" }}
              spacing={1}
              alignItems={{ xs: "stretch", sm: "center" }}
              justifyContent="space-between"
              sx={{ py: 0.25 }}
            >
              <Stack
                direction="row"
                spacing={1}
                alignItems="center"
                sx={{ minWidth: 0 }}
              >
                <JoyChip
                  color="neutral"
                  size="sm"
                  variant="soft"
                  sx={{ flexShrink: 0 }}
                >
                  {index + 1}
                </JoyChip>
                <Typography
                  level="body-sm"
                  sx={{ color: "neutral.800", overflowWrap: "anywhere" }}
                >
                  {option}
                </Typography>
              </Stack>
              <JoyButton
                color="neutral"
                size="sm"
                variant="outlined"
                onClick={() => onAction(`Use subject line: ${option}`)}
                sx={{ alignSelf: { xs: "flex-end", sm: "center" } }}
              >
                Use This
              </JoyButton>
            </Stack>
          ))}
        </Stack>
        <Divider
          sx={{ "--Divider-lineColor": "var(--joy-palette-neutral-100)" }}
        />
        <Box>
          <JoyButton
            color="primary"
            size="sm"
            variant="plain"
            onClick={() => onAction("Generate more subject lines")}
          >
            Generate More
          </JoyButton>
        </Box>
      </Stack>
    </JoyCard>
  );
}

function SingleContent({
  autoGenerated,
  characterLimit,
  content,
  contentType,
  onAction,
}: {
  autoGenerated: boolean;
  characterLimit: number | null | undefined;
  content: string;
  contentType: ContentBlockType;
  onAction: (prompt: string) => void;
}) {
  const count = content.length;
  const limit = characterLimit ?? null;
  const overLimit = limit !== null && count > limit;
  const title = CONTENT_TYPE_LABELS[contentType] ?? formatLabel(contentType);

  return (
    <JoyCard variant="outlined" sx={{ p: 1.5, width: "100%" }}>
      <Stack spacing={1.25}>
        <Header autoGenerated={autoGenerated} title={title} />
        <Divider
          sx={{ "--Divider-lineColor": "var(--joy-palette-neutral-100)" }}
        />
        <Box sx={{ maxHeight: 300, overflowY: "auto", pr: 0.5 }}>
          <Typography
            level="body-sm"
            sx={{
              color: "neutral.800",
              whiteSpace: "pre-wrap",
              overflowWrap: "anywhere",
              lineHeight: 1.7,
            }}
          >
            {content}
          </Typography>
        </Box>
        {contentType === "sms" && limit !== null ? (
          <Typography level="body-xs" color={overLimit ? "danger" : "neutral"}>
            {count}/{limit} characters
          </Typography>
        ) : null}
        <Stack
          direction="row"
          spacing={0.75}
          useFlexGap
          sx={{ flexWrap: "wrap" }}
        >
          <JoyButton
            color="neutral"
            size="sm"
            variant="outlined"
            startDecorator={<Copy size={14} strokeWidth={1.9} />}
            onClick={() => void copyToClipboard(content)}
          >
            Copy
          </JoyButton>
          <JoyButton
            color="neutral"
            size="sm"
            variant="outlined"
            startDecorator={<Clipboard size={14} strokeWidth={1.9} />}
            onClick={() => onAction("Use this content")}
          >
            Use This
          </JoyButton>
          <JoyButton
            color="neutral"
            size="sm"
            variant="plain"
            onClick={() => onAction("Make it shorter")}
          >
            Make Shorter
          </JoyButton>
          <JoyButton
            color="neutral"
            size="sm"
            variant="plain"
            onClick={() => onAction("Make it more formal")}
          >
            More Formal
          </JoyButton>
          <JoyButton
            color="primary"
            size="sm"
            variant="plain"
            startDecorator={<WandSparkles size={14} strokeWidth={1.9} />}
            onClick={() => onAction("Generate alternative content")}
          >
            Generate Alternatives
          </JoyButton>
        </Stack>
      </Stack>
    </JoyCard>
  );
}

export function ContentBlock({
  autoGenerated = false,
  characterLimit,
  content,
  contentType,
  onAction,
}: ContentBlockProps) {
  if (contentType === "subject_lines" && Array.isArray(content)) {
    return (
      <SubjectLineOptions
        autoGenerated={autoGenerated}
        content={content}
        onAction={onAction}
      />
    );
  }

  const textContent = Array.isArray(content) ? content.join("\n") : content;
  return (
    <SingleContent
      autoGenerated={autoGenerated}
      characterLimit={characterLimit}
      content={textContent}
      contentType={contentType}
      onAction={onAction}
    />
  );
}
