import { Helmet } from "react-helmet-async";
import { Link, useNavigate } from "react-router-dom";
import { Check, ClipboardCheck, PackageCheck, ScanLine, UsersRound, Search, CreditCard, Mail, RefreshCw, Camera, Layers3 } from "lucide-react";
import { LandingPageHeader } from "@/components/landing/LandingPageHeader";
import { POS_DEMO_HREF, POS_LOGIN_HREF } from "@/components/suite/products";
import "@/components/suite/suiteMarketing.css";

const features = [
  [ScanLine, "Keep the line moving", "Find plants and products, scan barcodes, adjust quantities, and work through the sale from a register designed for the counter."],
  [PackageCheck, "Give every product its place", "Manage your catalogue, pricing, photos, receiving, and inventory tasks from a dedicated manager workspace."],
  [UsersRound, "Help the person in front of you", "Keep customer lookup, trade accounts, returns, and store credit close to the everyday work of serving customers."],
  [ClipboardCheck, "Finish the day with clarity", "Review register sessions, cash counts, and reports so your team can see what needs attention before closing."],
] as const;

export function PosMarketingPage() {
  const navigate = useNavigate();
  return <div className="suite-marketing pos-marketing">
    <Helmet><title>BloomSuite POS — Point of Sale for Garden Centres</title><meta name="description" content="Explore BloomSuite POS: checkout, inventory, customers, and a manager workspace built for independent garden centres. Book a guided demo."/><link rel="canonical" href="https://bloomsuite.app/pos"/><meta property="og:title" content="BloomSuite POS — Built for the way your garden centre works"/><meta property="og:description" content="Keep the counter moving and the store organized. Explore BloomSuite POS and book a guided demonstration."/><meta property="og:url" content="https://bloomsuite.app/pos"/><meta property="og:type" content="website"/></Helmet>
    <LandingPageHeader onLogin={() => navigate("/suite")} />
    <main id="pos-main">
      <section className="pos-hero"><div className="suite-container">
        <div className="pos-hero-grid"><div><p className="suite-eyebrow">BloomSuite POS · Independent garden centres</p><h1>Built for the way your garden centre works.</h1><p className="pos-lead">Your website helps customers discover you. Your team serves them at the counter. Your CRM gives you a reason to welcome them back. BloomSuite POS brings the store into that same customer journey.</p><div className="suite-actions"><Link className="suite-button suite-button--primary" to={POS_DEMO_HREF}>Book a POS demo</Link><a className="suite-button" href={POS_LOGIN_HREF}>Log in to POS</a></div><p className="pos-demo-caption">Explore a guided demo with our team. We’ll walk through your store’s needs and readiness.</p></div>
        <div className="pos-screen-frame"><figure><img src="/pos/manager-workspace.webp" alt="BloomSuite POS manager workspace showing the store’s operational tools" width="1440" height="1000" fetchPriority="high"/><figcaption>The BloomSuite POS manager workspace, shown with demonstration data.</figcaption></figure></div></div>
        <div className="pos-proof-strip"><div><strong>At the counter</strong><p>A focused register for staff.</p></div><div><strong>Behind the scenes</strong><p>A workspace for running the store.</p></div><div><strong>Part of BloomSuite</strong><p>Website, checkout, and follow-up can share one customer story.</p></div></div>
      </div></section>
      <section className="pos-section pos-journey"><div className="suite-container">
        <div className="suite-section-heading"><p className="suite-eyebrow">One customer journey</p><h2>From the first search to the next visit.</h2><p>BloomSuite is designed around what a garden centre customer actually does—not around separate software screens.</p></div>
        <div className="pos-cycle" aria-label="BloomSuite customer journey">
          <article><span className="pos-cycle-icon"><Search size={22} aria-hidden="true"/></span><p className="pos-cycle-step">01 · Discover</p><h3>Find the garden centre</h3><p>BloomSites helps customers discover your store, plants, events, and seasonal offers.</p></article>
          <article><span className="pos-cycle-icon"><CreditCard size={22} aria-hidden="true"/></span><p className="pos-cycle-step">02 · Purchase</p><h3>Serve them well</h3><p>BloomSuite POS handles the counter, catalogue, receiving, stock, customer accounts, and the daily work behind the sale.</p></article>
          <article><span className="pos-cycle-icon"><Mail size={22} aria-hidden="true"/></span><p className="pos-cycle-step">03 · Follow up</p><h3>Remember the relationship</h3><p>With a verified connection, accepted sales and customer identity can feed CRM purchase history without guessing who someone is.</p></article>
          <article><span className="pos-cycle-icon"><RefreshCw size={22} aria-hidden="true"/></span><p className="pos-cycle-step">04 · Return</p><h3>Give them a reason to come back</h3><p>Use consented email, SMS, events, care content, and seasonal campaigns to earn the next visit.</p></article>
        </div>
      </div></section>
      <section className="pos-section" id="pos-capabilities"><div className="suite-container"><div className="suite-section-heading"><p className="suite-eyebrow">Make the everyday work easier</p><h2>From the first delivery to the last sale.</h2><p>Give staff a clear place to work and owners a clear view of the details.</p></div><div className="pos-feature-grid">{features.map(([Icon,title,description]) => <article className="pos-feature" key={title}><Icon size={28} aria-hidden="true"/><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
      <section className="pos-section"><div className="suite-container pos-split"><div className="pos-screen-frame"><figure><img src="/pos/catalogue-workspace.webp" alt="BloomSuite POS catalogue with visual product and pricing controls" width="1440" height="1000" loading="lazy"/><figcaption>The product catalogue, shown with demonstration data.</figcaption></figure></div><div><p className="suite-eyebrow">A catalogue built around what you sell</p><h2>Plants, products, and the details that matter.</h2><p>Your catalogue should help the team find the right item and keep its information useful.</p><ul className="pos-checklist">{["Find and organize the products your store sells.","Review product photos, variants, and prices.","Work on catalogue and inventory tasks away from the register."].map(text=><li key={text}><Check size={20} aria-hidden="true"/><span>{text}</span></li>)}</ul></div></div></section>
      <section className="pos-section" id="switching"><div className="suite-container pos-split"><div><p className="suite-eyebrow">Switch with a clear plan</p><h2>Start with your store. Keep what works.</h2><p>Moving to a new POS deserves care. We’ll review your current system, data, and hardware before recommending a transition.</p><p>Scanners, printers, drawers, scales, and payment devices need individual compatibility checks. We’ll tell you what can stay and what needs setup or replacement.</p><div className="suite-actions"><Link className="suite-button suite-button--primary" to={POS_DEMO_HREF}>Talk through your switch</Link></div></div><div className="pos-process"><article><h3>Show us how you work</h3><p>Walk through your current checkout, catalogue, locations, and reporting needs.</p></article><article><h3>Review the fit</h3><p>Check hardware compatibility and the records available from your existing system.</p></article><article><h3>Try it with your team</h3><p>Use a guided demo to validate the important workflows before planning a cutover.</p></article></div></div></section>
      <section className="pos-section pos-connect"><div className="suite-container"><div className="suite-section-heading"><p className="suite-eyebrow">One family of products</p><h2>The counter is part of a bigger picture.</h2><p>Explore the tools for serving customers, bringing them back, and helping them find you online.</p></div><div className="pos-connect-grid"><article><Layers3 size={26} aria-hidden="true"/><h3>One product story</h3><p>Keep the product your team edits at the centre of POS and website workflows instead of maintaining disconnected copies.</p></article><article><Camera size={26} aria-hidden="true"/><h3>Retailer photo choices</h3><p>When a product is explicitly paired, a retailer-selected POS gallery can publish to the matching BloomSites product with a durable receipt.</p></article><article><UsersRound size={26} aria-hidden="true"/><h3>Customer history with guardrails</h3><p>Verified customer mappings let CRM connect purchase history without silently merging people or inventing marketing consent.</p></article></div><p className="pos-connect-note">Connections are enabled per business and require verified tenant, product, and customer mappings. We show configured capabilities honestly rather than treating a logo as proof of a live sync.</p><div className="suite-actions"><Link className="suite-button suite-button--light" to="/features">Explore BloomSuite CRM</Link><a className="suite-button suite-button--light" href="https://bloomsites.app/">Explore BloomSites</a></div></div></section>
      <section className="pos-section"><div className="suite-container pos-faq"><h2>A few things you might be wondering.</h2><details><summary>Can I see the POS before committing?</summary><p>Yes. Book a guided demonstration so we can show the register and manager workspace, answer questions, and discuss your store’s requirements.</p></details><details><summary>Do I have to replace all my hardware?</summary><p>We start with a compatibility review. Some hardware may be reusable; payment terminals and specialized devices need their own checks. We’ll confirm the options for your equipment.</p></details><details><summary>Do I need the CRM or a BloomSites website to use POS?</summary><p>Tell us which products you need. We’ll review the POS setup independently and explain any available connections to your customer marketing and website.</p></details><details><summary>How much does it cost?</summary><p>We’ll discuss pricing with you after reviewing your locations, registers, hardware, payment needs, and onboarding scope. Existing CRM pricing is separate from a POS proposal.</p></details></div></section>
      <section className="pos-section pos-final"><div className="suite-container"><div className="suite-section-heading"><p className="suite-eyebrow">Let’s see it in action</p><h2>Bring your questions. We’ll bring the POS.</h2><p>See how BloomSuite POS could fit the way your garden centre works.</p></div><div className="suite-actions"><Link className="suite-button suite-button--primary" to={POS_DEMO_HREF}>Book a POS demo</Link><a className="suite-button" href={POS_LOGIN_HREF}>Already have an account? Log in</a></div></div></section>
    </main><footer className="suite-footer"><div className="suite-container"><strong>BloomSuite POS</strong><nav className="suite-footer-links" aria-label="POS footer"><Link to="/">BloomSuite</Link><a href="https://bloomsites.app/">BloomSites</a><Link to="/contact?product=pos">Contact</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></nav></div></footer>
  </div>;
}
