
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { ensureCampaignHasTasks } from "./homepage/CampaignAutoManager";
import { generateRequiredTasks } from "./homepage/RequiredTasksGenerator";
import { NewCampaignDialog } from "./homepage/NewCampaignDialog";
import { ReadyToPostCard } from "./homepage/ReadyToPostCard";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { getCurrentWeekNumber } from "@/utils/dateUtils";
import { getCurrentWeekCampaign } from "./homepage/homepageUtils";
import { HomepageHeader } from "./homepage/HomepageHeader";
import { HomepageActions } from "./homepage/HomepageActions";
import { HomepageMainContent } from "./homepage/HomepageMainContent";
import { HomepageSidebar } from "./homepage/HomepageSidebar";

interface Campaign {
  id: string;
  title: string;
  description: string | null;
  start_date: string;
  theme: string | null;
  week_number: number;
}

export const Homepage = () => {
  const { user } = useAuth();
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openNewCampaign, setOpenNewCampaign] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const fetchCampaigns = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('campaigns')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching campaigns:', error);
        toast.error('Failed to load campaigns');
      } else {
        setCampaigns(data || []);
      }
    } catch (error) {
      console.error('Error fetching campaigns:', error);
      toast.error('An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  const fetchTasks = async () => {
    try {
      const { data, error } = await supabase
        .from('content_tasks')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching tasks:', error);
      } else {
        setTasks(data || []);
      }
    } catch (error) {
      console.error('Error fetching tasks:', error);
    }
  };

  const handleCampaignCreate = async (newCampaign: Omit<Campaign, 'id'>) => {
    try {
      const { data, error } = await supabase
        .from('campaigns')
        .insert([newCampaign])
        .select()

      if (error) {
        console.error('Error creating campaign:', error);
        toast.error('Failed to create campaign');
      } else {
        setCampaigns(prevCampaigns => [data[0], ...prevCampaigns]);
        toast.success('Campaign created successfully');
        setOpenNewCampaign(false);
      }
    } catch (error) {
      console.error('Error creating campaign:', error);
      toast.error('An unexpected error occurred');
    }
  };

  const handleTaskUpdate = () => {
    fetchTasks();
  };

  // Auto-generate content for any campaign that needs it
  const autoGenerateContent = async () => {
    if (!user || hasAutoGenerated || campaigns.length === 0) return;
    
    console.log('Checking campaigns for auto-generation...');
    
    // First, try to find current week campaign
    const weekNumber = getCurrentWeekNumber();
    let targetCampaign = campaigns.find(c => c.week_number === weekNumber);
    
    // If no current week campaign, use the first available campaign
    if (!targetCampaign) {
      targetCampaign = campaigns[0];
      console.log(`No campaign for week ${weekNumber}, using first available:`, targetCampaign?.title);
    } else {
      console.log(`Found campaign for current week ${weekNumber}:`, targetCampaign.title);
    }
    
    if (targetCampaign) {
      // Check if this campaign already has any content
      const { data: existingTasks } = await supabase
        .from('content_tasks')
        .select('id')
        .eq('campaign_id', targetCampaign.id);
      
      if (!existingTasks || existingTasks.length === 0) {
        console.log('Auto-generating content for campaign:', targetCampaign.title);
        try {
          await generateRequiredTasks(targetCampaign.id, campaigns, user.id, handleTaskUpdate);
          toast.success(`Welcome! We've generated content for "${targetCampaign.title}" for you to review.`);
          setHasAutoGenerated(true);
        } catch (error) {
          console.error('Auto-generation failed:', error);
          // Don't show error toast for auto-generation to avoid annoying users
        }
      } else {
        console.log('Campaign already has content, skipping auto-generation');
      }
    }
  };

  useEffect(() => {
    if (user) {
      fetchCampaigns();
      fetchTasks();
    }
  }, [user]);

  useEffect(() => {
    if (campaigns.length > 0 && user) {
      ensureCampaignHasTasks(campaigns, user.id, handleTaskUpdate);
      // Auto-generate content after ensuring campaigns exist
      autoGenerateContent();
    }
  }, [campaigns, user, hasAutoGenerated]);

  const handleThemesGenerated = () => {
    fetchCampaigns();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <HomepageHeader 
            onNewCampaignClick={() => setOpenNewCampaign(true)} 
            onImportComplete={fetchCampaigns} 
          />
          
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-primary" />
              <p className="text-primary font-medium text-lg">Loading your campaigns and content...</p>
              <p className="text-gray-500 text-sm mt-2">Setting up your marketing workspace</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const weekNumber = getCurrentWeekNumber();
  
  // Always prioritize finding a campaign for the current week
  let currentCampaign = campaigns.find(c => c.week_number === weekNumber);
  
  // If no campaign exists for current week, we should indicate this clearly
  // rather than falling back to week 1
  if (!currentCampaign && campaigns.length > 0) {
    console.log(`No campaign found for current week ${weekNumber}, available weeks:`, 
      campaigns.map(c => c.week_number));
  }

  return (
    <div className="min-h-screen bg-garden-background p-6">
      <div className="max-w-5xl mx-auto space-y-8">
        <HomepageHeader 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        <HomepageActions 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        {/* Add Ready to Post section */}
        <ReadyToPostCard 
          tasks={tasks}
          onTaskUpdate={handleTaskUpdate}
        />

        <div className="grid lg:grid-cols-3 gap-6">
          <HomepageMainContent 
            currentCampaign={currentCampaign}
            onTaskUpdate={handleTaskUpdate}
          />
          
          <HomepageSidebar onThemesGenerated={handleThemesGenerated} />
        </div>
      </div>

      <NewCampaignDialog 
        open={openNewCampaign} 
        onOpenChange={setOpenNewCampaign} 
        onCreate={handleCampaignCreate} 
      />
    </div>
  );
};
