
import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { ensureCampaignHasTasks } from "./homepage/CampaignAutoManager";
import { generateRequiredTasks } from "./homepage/RequiredTasksGenerator";
import { NewCampaignDialog } from "./homepage/NewCampaignDialog";
import { ReadyToPostCard } from "./homepage/ReadyToPostCard";
import { ReviewQueueCard } from "./content/ReviewQueueCard";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { getCurrentWeekNumber } from "@/utils/dateUtils";
import { getCurrentWeekCampaign } from "./homepage/homepageUtils";
import { HomepageHeader } from "./homepage/HomepageHeader";
import { HomepageActions } from "./homepage/HomepageActions";
import { HomepageMainContent } from "./homepage/HomepageMainContent";
import { HomepageSidebar } from "./homepage/HomepageSidebar";

interface Campaign {
  id: string;
  title: string;
  description: string | null;
  start_date: string;
  theme: string | null;
  week_number: number;
  user_id: string;
}

export const Homepage = () => {
  const { user } = useAuth();
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openNewCampaign, setOpenNewCampaign] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const fetchCampaigns = async () => {
    if (!user) {
      console.log('Homepage: No authenticated user, skipping campaign fetch');
      setLoading(false);
      return;
    }

    setLoading(true);
    try {
      console.log('Homepage: Fetching campaigns for user:', user.id);
      
      // SECURITY FIX: Explicitly filter campaigns by current user
      const { data, error } = await supabase
        .from('campaigns')
        .select('*')
        .eq('user_id', user.id)  // CRITICAL: Only fetch current user's campaigns
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Homepage: Error fetching campaigns:', error);
        toast.error('Failed to load campaigns');
      } else {
        console.log('Homepage: Successfully fetched', data?.length || 0, 'campaigns for user', user.id);
        
        // Additional security verification
        const userCampaigns = data?.filter(campaign => campaign.user_id === user.id) || [];
        if (userCampaigns.length !== data?.length) {
          console.warn('Homepage: Security alert - some campaigns did not belong to current user');
        }
        
        setCampaigns(userCampaigns);
      }
    } catch (error) {
      console.error('Homepage: Error fetching campaigns:', error);
      toast.error('An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  const fetchTasks = async () => {
    if (!user) {
      console.log('Homepage: No authenticated user, skipping task fetch');
      return;
    }

    try {
      console.log('Homepage: Fetching tasks for user:', user.id);
      
      // SECURITY FIX: Use inner join to ensure we only get tasks for user's campaigns
      // Updated to include holiday content tasks
      const { data, error } = await supabase
        .from('content_tasks')
        .select(`
          *,
          campaigns!inner (
            title,
            user_id
          ),
          holidays (
            holiday_name,
            holiday_date
          )
        `)
        .eq('campaigns.user_id', user.id)  // CRITICAL: Filter by current user
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Homepage: Error fetching tasks:', error);
      } else {
        console.log('Homepage: Successfully fetched', data?.length || 0, 'tasks for user', user.id);
        
        // Additional security verification
        const userTasks = data?.filter(task => 
          task.campaigns && task.campaigns.user_id === user.id
        ) || [];
        
        if (userTasks.length !== data?.length) {
          console.warn('Homepage: Security alert - some tasks did not belong to current user');
        }
        
        setTasks(userTasks);
      }
    } catch (error) {
      console.error('Homepage: Error fetching tasks:', error);
    }
  };

  const handleCampaignCreate = async (newCampaign: Omit<Campaign, 'id'>) => {
    // Campaign is already created in the dialog, just refresh the list
    await fetchCampaigns();
    toast.success('Campaign created successfully');
    setOpenNewCampaign(false);
  };

  const handleTaskUpdate = () => {
    fetchTasks();
  };

  // Auto-generate content for any campaign that needs it
  const autoGenerateContent = async () => {
    if (!user || hasAutoGenerated || campaigns.length === 0) return;
    
    console.log('Homepage: Checking campaigns for auto-generation for user:', user.id);
    
    // First, try to find current week campaign
    const weekNumber = getCurrentWeekNumber();
    let targetCampaign = campaigns.find(c => c.week_number === weekNumber);
    
    // If no current week campaign, use the first available campaign
    if (!targetCampaign) {
      targetCampaign = campaigns[0];
      console.log(`Homepage: No campaign for week ${weekNumber}, using first available:`, targetCampaign?.title);
    } else {
      console.log(`Homepage: Found campaign for current week ${weekNumber}:`, targetCampaign.title);
    }
    
    if (targetCampaign && targetCampaign.user_id === user.id) {
      // SECURITY CHECK: Verify campaign belongs to current user
      const { data: existingTasks } = await supabase
        .from('content_tasks')
        .select('id')
        .eq('campaign_id', targetCampaign.id);
      
      if (!existingTasks || existingTasks.length === 0) {
        console.log('Homepage: Auto-generating content for user campaign:', targetCampaign.title);
        try {
          await generateRequiredTasks(targetCampaign.id, campaigns, user.id, handleTaskUpdate);
          toast.success(`Welcome! We've generated content for "${targetCampaign.title}" for you to review.`);
          setHasAutoGenerated(true);
        } catch (error) {
          console.error('Homepage: Auto-generation failed:', error);
          // Don't show error toast for auto-generation to avoid annoying users
        }
      } else {
        console.log('Homepage: Campaign already has content, skipping auto-generation');
      }
    }
  };

  useEffect(() => {
    if (user) {
      fetchCampaigns();
      fetchTasks();
    }
  }, [user]);

  useEffect(() => {
    if (campaigns.length > 0 && user) {
      ensureCampaignHasTasks(campaigns, user.id, handleTaskUpdate);
      // Auto-generate content after ensuring campaigns exist
      autoGenerateContent();
    }
  }, [campaigns, user, hasAutoGenerated]);

  const handleThemesGenerated = () => {
    fetchCampaigns();
  };

  // Early return if no authenticated user
  if (!user) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <p className="text-garden-green font-medium text-lg">Please log in to access your campaigns</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <HomepageHeader 
            onNewCampaignClick={() => setOpenNewCampaign(true)} 
            onImportComplete={fetchCampaigns} 
          />
          
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-garden-green" />
              <p className="text-garden-green font-medium text-lg">Loading your campaigns and content...</p>
              <p className="text-gray-500 text-sm mt-2">Setting up your marketing workspace</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const weekNumber = getCurrentWeekNumber();
  
  // Always prioritize finding a campaign for the current week
  let currentCampaign = campaigns.find(c => c.week_number === weekNumber);
  
  // If no campaign exists for current week, we should indicate this clearly
  // rather than falling back to week 1
  if (!currentCampaign && campaigns.length > 0) {
    console.log(`Homepage: No campaign found for current week ${weekNumber}, available weeks:`, 
      campaigns.map(c => c.week_number));
  }

  return (
    <div className="min-h-screen bg-garden-background p-6">
      <div className="max-w-5xl mx-auto space-y-8">
        <HomepageHeader 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        <HomepageActions 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        {/* Review Queue - Only show if there are tasks to review */}
        <ReviewQueueCard onTaskUpdate={handleTaskUpdate} />

        {/* Ready to Post section */}
        <ReadyToPostCard 
          tasks={tasks}
          onTaskUpdate={handleTaskUpdate}
        />

        <div className="grid lg:grid-cols-3 gap-6">
          <HomepageMainContent 
            currentCampaign={currentCampaign}
            onTaskUpdate={handleTaskUpdate}
          />
          
          <HomepageSidebar onThemesGenerated={handleThemesGenerated} />
        </div>
      </div>

      <NewCampaignDialog 
        open={openNewCampaign} 
        onOpenChange={setOpenNewCampaign} 
        onCreate={handleCampaignCreate} 
      />
    </div>
  );
};
