import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useTenant } from "@/hooks/useTenant";
import { ensureCampaignHasTasks } from "./homepage/CampaignAutoManager";
import { generateRequiredTasks } from "./homepage/RequiredTasksGenerator";
import { NewCampaignDialog } from "./homepage/NewCampaignDialog";
import { ReadyToPostCard } from "./homepage/ReadyToPostCard";
import { ReviewQueueCard } from "./content/ReviewQueueCard";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { getCurrentWeekNumber } from "@/utils/dateUtils";
import { getCurrentWeekCampaign } from "./homepage/homepageUtils";
import { HomepageHeader } from "./homepage/HomepageHeader";
import { HomepageActions } from "./homepage/HomepageActions";
import { HomepageMainContent } from "./homepage/HomepageMainContent";
import { HomepageSidebar } from "./homepage/HomepageSidebar";
import { Campaign } from "@/types/content";

export const Homepage = () => {
  const { user } = useAuth();
  const { tenant, loading: tenantLoading } = useTenant();
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openNewCampaign, setOpenNewCampaign] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Check if user is developer
  const isDeveloper = user?.email === 'jon@getclear.ca';

  const fetchCampaigns = async () => {
    if (!user || !tenant) {
      console.log('Homepage: No authenticated user or tenant, skipping campaign fetch');
      setLoading(false);
      return;
    }

    setLoading(true);
    try {
      console.log('Homepage: Fetching campaigns for tenant:', tenant.id);
      
      // SECURITY FIX: Filter campaigns by current tenant
      const { data, error } = await supabase
        .from('campaigns')
        .select('*')
        .eq('tenant_id', tenant.id)  // CRITICAL: Only fetch current tenant's campaigns
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Homepage: Error fetching campaigns:', error);
        toast.error('Failed to load campaigns');
      } else {
        console.log('Homepage: Successfully fetched', data?.length || 0, 'campaigns for tenant', tenant.id);
        setCampaigns(data || []);
      }
    } catch (error) {
      console.error('Homepage: Error fetching campaigns:', error);
      toast.error('An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  const fetchTasks = async () => {
    if (!user || !tenant) {
      console.log('Homepage: No authenticated user or tenant, skipping task fetch');
      return;
    }

    try {
      console.log('Homepage: Fetching tasks for tenant:', tenant.id);
      
      // Build status filter - include 'preview' for developer
      const statusFilter = ['planned', 'review', 'approved', 'posted', 'generated', 'pending'];
      if (isDeveloper) {
        statusFilter.push('preview');
      }

      const { data, error } = await supabase
        .from('content_tasks')
        .select(`
          *,
          campaigns!inner (
            title,
            tenant_id
          ),
          holidays (
            holiday_name,
            holiday_date
          )
        `)
        .eq('tenant_id', tenant.id)  // CRITICAL: Filter by current tenant
        .in('status', statusFilter)  // Include preview for developers
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Homepage: Error fetching tasks:', error);
      } else {
        console.log('Homepage: Successfully fetched', data?.length || 0, 'tasks for tenant', tenant.id);
        setTasks(data || []);
      }
    } catch (error) {
      console.error('Homepage: Error fetching tasks:', error);
    }
  };

  const handleCampaignCreate = async (newCampaign: Campaign) => {
    await fetchCampaigns();
    toast.success('Campaign created successfully');
    setOpenNewCampaign(false);
  };

  const handleTaskUpdate = () => {
    fetchTasks();
  };

  const autoGenerateContent = async () => {
    if (!user || !tenant || hasAutoGenerated || campaigns.length === 0) return;
    
    console.log('Homepage: Checking campaigns for auto-generation for tenant:', tenant.id);
    
    const weekNumber = getCurrentWeekNumber();
    let targetCampaign = campaigns.find(c => c.week_number === weekNumber);
    
    if (!targetCampaign) {
      targetCampaign = campaigns[0];
      console.log(`Homepage: No campaign for week ${weekNumber}, using first available:`, targetCampaign?.title);
    } else {
      console.log(`Homepage: Found campaign for current week ${weekNumber}:`, targetCampaign.title);
    }
    
    if (targetCampaign && targetCampaign.tenant_id === tenant.id) {
      const { data: existingTasks } = await supabase
        .from('content_tasks')
        .select('id')
        .eq('campaign_id', targetCampaign.id);
      
      if (!existingTasks || existingTasks.length === 0) {
        console.log('Homepage: Auto-generating content for tenant campaign:', targetCampaign.title);
        try {
          await generateRequiredTasks(targetCampaign.id, campaigns, user.id, handleTaskUpdate);
          toast.success(`Welcome! We've generated content for "${targetCampaign.title}" for you to review.`);
          setHasAutoGenerated(true);
        } catch (error) {
          console.error('Homepage: Auto-generation failed:', error);
        }
      } else {
        console.log('Homepage: Campaign already has content, skipping auto-generation');
      }
    }
  };

  useEffect(() => {
    if (user && !tenantLoading) {
      fetchCampaigns();
      fetchTasks();
    }
  }, [user, tenant, tenantLoading]);

  useEffect(() => {
    if (campaigns.length > 0 && user && tenant) {
      ensureCampaignHasTasks(campaigns, user.id, handleTaskUpdate);
      autoGenerateContent();
    }
  }, [campaigns, user, tenant, hasAutoGenerated]);

  const handleThemesGenerated = () => {
    fetchCampaigns();
  };

  // Early return if no authenticated user or tenant is loading
  if (!user || tenantLoading) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-garden-green" />
              <p className="text-garden-green font-medium text-lg">
                {!user ? 'Please log in to access your campaigns' : 'Loading your workspace...'}
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Show tenant assignment message if user has no tenant
  if (!tenant) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <p className="text-garden-green font-medium text-lg">Setting up your workspace...</p>
              <p className="text-gray-500 text-sm mt-2">Please contact support to assign you to an organization.</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-garden-background">
        <div className="max-w-5xl mx-auto p-6">
          <HomepageHeader 
            onNewCampaignClick={() => setOpenNewCampaign(true)} 
            onImportComplete={fetchCampaigns} 
          />
          
          <div className="flex justify-center items-center py-20">
            <div className="text-center">
              <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-garden-green" />
              <p className="text-garden-green font-medium text-lg">Loading your campaigns and content...</p>
              <p className="text-gray-500 text-sm mt-2">Setting up your marketing workspace</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const weekNumber = getCurrentWeekNumber();
  let currentCampaign = campaigns.find(c => c.week_number === weekNumber);
  
  if (!currentCampaign && campaigns.length > 0) {
    console.log(`Homepage: No campaign found for current week ${weekNumber}, available weeks:`, 
      campaigns.map(c => c.week_number));
  }

  return (
    <div className="min-h-screen bg-garden-background p-6">
      <div className="max-w-5xl mx-auto space-y-8">
        <HomepageHeader 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        <HomepageActions 
          onNewCampaignClick={() => setOpenNewCampaign(true)} 
          onImportComplete={fetchCampaigns} 
        />

        <ReviewQueueCard onTaskUpdate={handleTaskUpdate} />

        <ReadyToPostCard 
          tasks={tasks}
          onTaskUpdate={handleTaskUpdate}
        />

        <div className="grid lg:grid-cols-3 gap-6">
          <HomepageMainContent 
            currentCampaign={currentCampaign}
            onTaskUpdate={handleTaskUpdate}
          />
          
          <HomepageSidebar onThemesGenerated={handleThemesGenerated} />
        </div>
      </div>

      <NewCampaignDialog 
        open={openNewCampaign} 
        onOpenChange={setOpenNewCampaign} 
        onCreate={handleCampaignCreate} 
      />
    </div>
  );
};
