
import { parseNewsletterYAML } from './newsletterUtils';
import { cleanContentForDisplay, truncateText } from './contentUtils';
import { markdownToHtmlBlocks, extractKeywordsFromContent } from './markdownUtils';
import { processUniversalContent } from './universalContentProcessor';
import { ContentTask } from '@/types/content';

export interface NormalizedTask {
  id: string;
  post_type: string;
  ai_output: string;
  image_prompts?: string[];
  normalized?: any;
  teaser_html?: string;
  title?: string;
  status?: string;
  campaigns?: any;
  [key: string]: any;
}

export function normalizeTask(task: any): NormalizedTask {
  if (!task) return task;
  
  const out = { ...task };

  // 1. Use universal content processor for all content types
  const processed = processUniversalContent(out as ContentTask);
  
  // 2. Apply the structured format to the task
  if (processed.blocks.length > 0) {
    out.blocks = processed.blocks;
    out.metadata = processed.metadata;
    out.extra_content_ideas = processed.extra_content_ideas;
    
    // Maintain backward compatibility with existing normalized structure
    if (out.post_type === 'newsletter') {
      out.normalized = {
        newsletter_md: out.ai_output,
        blocks: processed.blocks,
        extra_content_ideas: processed.extra_content_ideas,
        meta: processed.metadata
      };
    }
    
    // Extract image prompts for backward compatibility
    out.image_prompts = processed.metadata.image_prompts || [];
  }

  // 3. Fallback image prompts if not generated by processor
  if (!Array.isArray(out.image_prompts) || !out.image_prompts.length) {
    const contentKeywords = extractKeywordsFromContent(out.ai_output);
    const campaignTheme = out.campaigns?.theme || '';
    const themeKeywords = extractKeywordsFromContent(campaignTheme, 'seasonal');
    out.image_prompts = [...contentKeywords, ...themeKeywords.slice(0, 2)];
  }

  // 4. Generate teaser for blog content
  if (out.post_type === 'blog' && !out.teaser_html) {
    const firstBlock = out.blocks?.[0];
    if (firstBlock?.body) {
      out.teaser_html = truncateText(firstBlock.body, 300, '...');
    } else {
      const blocks = markdownToHtmlBlocks(out.ai_output || '');
      const firstParagraph = blocks.find(b => b.type === 'paragraph')?.body;
      out.teaser_html = firstParagraph ? truncateText(firstParagraph, 300, '...') : '';
    }
  }

  // 5. Clean content for display (but preserve YAML structure for newsletters)
  if (out.post_type === 'newsletter') {
    // For newsletters, preserve the original YAML structure for proper processing
    out.display_content = out.ai_output || '';
  } else {
    out.display_content = cleanContentForDisplay(out.ai_output || '', out.post_type);
  }

  return out;
}

// Batch normalize multiple tasks
export function normalizeTasks(tasks: any[]): NormalizedTask[] {
  if (!Array.isArray(tasks)) return [];
  return tasks.map(normalizeTask);
}

// Check if a task needs normalization
export function needsNormalization(task: any): boolean {
  if (!task) return false;
  
  // Check for missing image_prompts
  if (!Array.isArray(task.image_prompts) || task.image_prompts.length === 0) {
    return true;
  }
  
  // Check for newsletter without normalized format
  if (task.post_type === 'newsletter' && !task.normalized && task.ai_output) {
    const isStructured = task.ai_output.includes('newsletter_md:') || task.ai_output.includes('blocks:');
    return !isStructured;
  }
  
  // Check for blog without teaser
  if (task.post_type === 'blog' && task.ai_output && !task.teaser_html) {
    return true;
  }
  
  return false;
}
