
import { Textarea } from "@/components/ui/textarea";
import { SafeHtml } from "@/components/ui/safe-html";
import { cleanContentForDisplay } from "@/utils/contentUtils";
import { MagazineNewsletterDisplay } from "./MagazineNewsletterDisplay";
import { MagazineContentDisplay } from "@/components/content/task-item/MagazineContentDisplay";
import { SocialMediaPostPreview } from "@/components/content/task-item/SocialMediaPostPreview";

interface ContentEditorProps {
  content: string;
  onContentChange: (content: string) => void;
  task: any;
  isEditing?: boolean;
}

export const ContentEditor = ({ content, onContentChange, task, isEditing = false }: ContentEditorProps) => {
  const getPlaceholderText = () => {
    if (task?.status === 'generating') {
      return "AI is currently generating content for this post...";
    } else if (task?.status === 'planned') {
      return "Content will be generated when this task moves to generating status...";
    } else {
      return `Write your ${task?.post_type} content here...`;
    }
  };

  if (isEditing) {
    return (
      <div className="space-y-2">
        <h3 className="text-sm font-medium text-gray-700">Content</h3>
        <Textarea
          value={content}
          onChange={(e) => onContentChange(e.target.value)}
          placeholder={getPlaceholderText()}
          className="min-h-[400px] resize-none"
        />
      </div>
    );
  }

  // Check if this is a social media post for special preview handling
  const isSocialMediaPost = task?.post_type === 'instagram' || task?.post_type === 'facebook';
  
  // Check if this is a structured newsletter for magazine display
  const isStructuredNewsletter = task?.post_type === 'newsletter' && content.includes('newsletter_md:');
  
  return (
    <div className="space-y-2">
      <h3 className="text-sm font-medium text-gray-700">Content</h3>
      <div className="p-6 bg-white rounded-lg border min-h-[400px] overflow-y-auto max-h-[800px]">
        {content ? (
          isSocialMediaPost ? (
            <SocialMediaPostPreview 
              content={content}
              postType={task.post_type as 'instagram' | 'facebook'}
              contentTaskId={task.id}
            />
          ) : isStructuredNewsletter ? (
            <MagazineNewsletterDisplay 
              content={content} 
              contentTaskId={task?.id}
              taskStatus={task?.status}
            />
          ) : task?.post_type === 'newsletter' ? (
            <MagazineContentDisplay
              content={content}
              postType={task.post_type}
              contentTaskId={task?.id}
              campaignTitle={task?.campaigns?.title}
              task={task}
            />
          ) : (task?.post_type === 'blog') ? (
            <SafeHtml
              content={cleanContentForDisplay(content, task?.post_type)}
              className="text-sm prose prose-sm max-w-none"
              type="social"
            />
          ) : (
            <div className="text-sm whitespace-pre-wrap">
              {cleanContentForDisplay(content, task?.post_type).replace(/<[^>]*>/g, '')}
            </div>
          )
        ) : (
          <span className="text-gray-400 italic">
            {task?.status === 'generating' ? 
              "Content is being generated by AI. Please wait..." : 
              "No content available yet."
            }
          </span>
        )}
      </div>
    </div>
  );
};
