
import { Textarea } from "@/components/ui/textarea";

interface ContentEditorProps {
  content: string;
  onContentChange: (content: string) => void;
  task: any;
}

export const ContentEditor = ({ content, onContentChange, task }: ContentEditorProps) => {
  const getPlaceholderText = () => {
    if (task?.status === 'generating') {
      return "AI is currently generating content for this post...";
    } else if (task?.status === 'planned') {
      return "Content will be generated when this task moves to generating status...";
    } else {
      return `Write your ${task?.post_type} content here...`;
    }
  };

  return (
    <div>
      <label className="text-sm font-medium text-gray-700 block mb-2">
        Content
      </label>
      <Textarea
        value={content}
        onChange={(e) => onContentChange(e.target.value)}
        placeholder={getPlaceholderText()}
        className="min-h-[200px]"
      />
      {task?.status === 'generating' && (
        <p className="text-xs text-blue-600 mt-1">
          Content is being generated by AI. Please wait...
        </p>
      )}
    </div>
  );
};
