import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

interface PersonaMetrics {
  persona_name: string;
  customer_count: number;
  total_revenue: number;
  avg_order_value: number;
  email_open_rate: number;
  sms_click_rate: number;
  engagement_score: number;
}

interface PersonaPerformanceChartProps {
  data: PersonaMetrics[];
  isLoading: boolean;
}

const COLORS = ['#22C55E', '#3B82F6', '#8B5CF6', '#F59E0B', '#EF4444', '#06B6D4', '#84CC16', '#F97316', '#EC4899'];

export function PersonaPerformanceChart({ data, isLoading }: PersonaPerformanceChartProps) {
  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Persona Performance</CardTitle>
          <CardDescription>Loading persona analytics...</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  const revenueData = data.map(item => ({
    name: item.persona_name.replace(' ', '\n'),
    revenue: item.total_revenue,
    customers: item.customer_count,
    avg_order: item.avg_order_value
  }));

  const engagementData = data.map(item => ({
    name: item.persona_name,
    email_rate: item.email_open_rate,
    sms_rate: item.sms_click_rate,
    score: item.engagement_score
  }));

  const pieData = data.map((item, index) => ({
    name: item.persona_name,
    value: item.customer_count,
    color: COLORS[index % COLORS.length]
  }));

  return (
    <div className="grid gap-6 md:grid-cols-2">
      {/* Revenue by Persona */}
      <Card>
        <CardHeader>
          <CardTitle>Revenue by Persona</CardTitle>
          <CardDescription>Total revenue generated by each customer persona</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={revenueData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis 
                dataKey="name" 
                tick={{ fontSize: 12 }}
                interval={0}
                angle={-45}
                textAnchor="end"
                height={80}
              />
              <YAxis tick={{ fontSize: 12 }} />
              <Bar dataKey="revenue" fill="#22C55E" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      {/* Customer Distribution */}
      <Card>
        <CardHeader>
          <CardTitle>Customer Distribution</CardTitle>
          <CardDescription>Breakdown of customers by persona type</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={pieData}
                cx="50%"
                cy="50%"
                labelLine={false}
                label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                outerRadius={80}
                fill="#8884d8"
                dataKey="value"
              >
                {pieData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
            </PieChart>
          </ResponsiveContainer>
          <div className="mt-4 grid grid-cols-2 gap-2">
            {pieData.map((entry, index) => (
              <div key={entry.name} className="flex items-center gap-2 text-sm">
                <div 
                  className="w-3 h-3 rounded-full" 
                  style={{ backgroundColor: entry.color }}
                />
                <span className="truncate">{entry.name}: {entry.value}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Engagement Rates */}
      <Card>
        <CardHeader>
          <CardTitle>Engagement Rates</CardTitle>
          <CardDescription>Email and SMS performance by persona</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={engagementData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis 
                dataKey="name" 
                tick={{ fontSize: 10 }}
                interval={0}
                angle={-45}
                textAnchor="end"
                height={80}
              />
              <YAxis tick={{ fontSize: 12 }} />
              <Bar dataKey="email_rate" fill="#3B82F6" name="Email Open Rate" />
              <Bar dataKey="sms_rate" fill="#8B5CF6" name="SMS Click Rate" />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      {/* Performance Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Performance Summary</CardTitle>
          <CardDescription>Key metrics comparison across personas</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {data.slice(0, 5).map((persona, index) => (
              <div key={persona.persona_name} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                <div className="flex items-center gap-3">
                  <div 
                    className="w-4 h-4 rounded-full" 
                    style={{ backgroundColor: COLORS[index % COLORS.length] }}
                  />
                  <div>
                    <p className="font-medium">{persona.persona_name}</p>
                    <p className="text-sm text-muted-foreground">
                      {persona.customer_count} customers
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="font-medium">${persona.total_revenue.toLocaleString()}</p>
                  <p className="text-sm text-muted-foreground">
                    ${persona.avg_order_value.toFixed(0)} avg
                  </p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}