
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udldmkqwnxhdeztyqcau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbGRta3F3bnhoZGV6dHlxY2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTg0MzQsImV4cCI6MjA2NDYzNDQzNH0.1iO2-DRx5aX_WpEcDGv9aKHGy1rdDPOZaQC6Ke4MpRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      'x-application-name': 'bloom-boost-marketing-hub',
    },
  },
});

// Enhanced error handling for offline scenarios
const originalFrom = supabase.from;
supabase.from = function(table: string) {
  const query = originalFrom.call(this, table);
  
  // Override the query methods to add better error handling
  const originalSelect = query.select;
  query.select = function(...args: any[]) {
    const result = originalSelect.apply(this, args);
    
    // Add offline handling to the promise
    if (result && typeof result.then === 'function') {
      return result.catch((error: any) => {
        if (!navigator.onLine || error.message?.includes('Failed to fetch')) {
          console.warn('Offline: Using cached data or returning empty result');
          return { data: [], error: { message: 'Offline - using cached data', isOffline: true } };
        }
        throw error;
      });
    }
    
    return result;
  };
  
  return query;
};
