// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { cachedSupabaseFetch } from "./cachedFetch";
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "./config";

const AUTH_STORAGE_KEYS = [
  "supabase.auth.token",
  "sb-udldmkqwnxhdeztyqcau-auth-token",
  "supabase.auth.refreshToken",
  "supabase.auth.expiresAt",
];

const hasAuthStorageMatch = (key: string) =>
  AUTH_STORAGE_KEYS.includes(key) ||
  key.startsWith("supabase.auth.") ||
  key.includes("sb-udld") ||
  key.includes("sb-auth") ||
  key.includes("-auth-token");

const shouldDetectSupabaseSessionInUrl = () => {
  if (typeof window === "undefined") {
    return true;
  }

  const { pathname, search, hash } = window.location;

  if (pathname === "/dashboard" || pathname === "/reset-password") {
    return true;
  }

  if (pathname.startsWith("/onboarding")) {
    return true;
  }

  // Provider-managed OAuth callbacks also use `?code=` query params.
  // Letting Supabase auto-consume those codes clears the active app session.
  if (pathname === "/auth/callback" || pathname.startsWith("/integrations/")) {
    return false;
  }

  // Keep supporting token/hash based recovery and invite flows even when
  // they land on a non-standard route.
  return (
    search.includes("type=recovery") ||
    search.includes("type=invite") ||
    search.includes("type=magiclink") ||
    search.includes("token_hash=") ||
    hash.includes("access_token=") ||
    hash.includes("refresh_token=")
  );
};

export const hasPersistedAuthState = () => {
  if (typeof localStorage === "undefined") {
    return false;
  }

  return Object.keys(localStorage).some(hasAuthStorageMatch);
};

// Enhanced auth state cleanup utility
export const cleanupAuthState = () => {
  try {
    // Remove all possible auth-related keys from localStorage
    AUTH_STORAGE_KEYS.forEach((key) => {
      localStorage.removeItem(key);
    });

    // Remove all Supabase auth keys with pattern matching
    Object.keys(localStorage).forEach((key) => {
      if (hasAuthStorageMatch(key)) {
        localStorage.removeItem(key);
      }
    });

    // Remove from sessionStorage if in use
    if (typeof sessionStorage !== "undefined") {
      Object.keys(sessionStorage).forEach((key) => {
        if (hasAuthStorageMatch(key)) {
          sessionStorage.removeItem(key);
        }
      });
    }
  } catch (error) {
    console.error("❌ Error during auth cleanup:", error);
  }
};

// Force logout utility for emergency situations
export const forceLogout = async () => {
  try {
    // Step 1: Clean up all auth state first
    cleanupAuthState();

    // Step 2: Clear any app-specific state
    localStorage.removeItem("subscription-cache");
    localStorage.removeItem("user-profile-cache");

    // Step 3: Attempt graceful signout (may fail in limbo state)
    try {
      await supabase.auth.signOut({ scope: "global" });
    } catch {
      // Ignore sign-out cleanup failures and continue forcing local reset.
    }

    // Step 4: Force page reload to completely reset state
    window.location.href = "/auth";
  } catch (error) {
    console.error("❌ Force logout error:", error);
    // Even if everything fails, try to redirect
    window.location.href = "/auth";
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      fetch: cachedSupabaseFetch,
    },
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: shouldDetectSupabaseSessionInUrl(),
      flowType: "pkce",
    },
  },
);

// Enhanced auth helpers with better error handling
export const signOutCompletely = async () => {
  try {
    // Clean up auth state first
    cleanupAuthState();

    // Attempt global sign out
    const { error } = await supabase.auth.signOut({ scope: "global" });
    if (error) {
      console.error("Sign out error (continuing anyway):", error);
    }

    // Force page reload for clean state
    window.location.href = "/auth";
  } catch (error) {
    console.error("Complete sign out error:", error);
    // Force cleanup and redirect anyway
    forceLogout();
  }
};

export const signInWithCleanup = async (email: string, password: string) => {
  // Clean up existing state
  cleanupAuthState();

  // Attempt global sign out first
  try {
    await supabase.auth.signOut({ scope: "global" });
  } catch {
    // Ignore pre-sign-in cleanup failures and continue with fresh credentials.
  }

  // Sign in with email/password
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  return { data, error };
};

export const signUpWithCleanup = async (
  email: string,
  password: string,
  fullName: string,
) => {
  // Clean up existing state
  cleanupAuthState();

  // Attempt global sign out first
  try {
    await supabase.auth.signOut({ scope: "global" });
  } catch {
    // Ignore pre-sign-up cleanup failures and continue with account creation.
  }

  const redirectUrl = `${window.location.origin}/onboarding`;

  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      emailRedirectTo: redirectUrl,
      data: {
        full_name: fullName,
      },
    },
  });

  return { data, error };
};
